apiVersion: v1
kind: Secret
metadata:
  name: authentik-secrets
  namespace: auth
type: Opaque
stringData:
  postgresql-admin-password: ${secrets_apps_auth_authentik_postgresqlAdminPassword}
  postgresql-user-password: ${secrets_apps_auth_authentik_postgresqlUserPassword}
  redis-password: ${secrets_apps_auth_authentik_redisPassword}
