apiVersion: v1
kind: Service
metadata:
  name: authentik-outpost-ldap
  namespace: auth
  labels:
    app.kubernetes.io/name: "authentik"
    app.kubernetes.io/instance: "authentik"
    app.kubernetes.io/component: "outpost-ldap"
spec:
  type: ClusterIP
  ports:
    - name: ldap
      port: 389
      protocol: TCP
      targetPort: ldap
    - name: ldaps
      port: 636
      protocol: TCP
      targetPort: ldaps
  selector:
    app.kubernetes.io/name: "authentik"
    app.kubernetes.io/instance: "authentik"
    app.kubernetes.io/component: "outpost-ldap"
