apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentik-worker
  namespace: auth
  labels:
    app.kubernetes.io/name: worker
    app.kubernetes.io/instance: authentik
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: worker
      app.kubernetes.io/instance: authentik
  template:
    metadata:
      labels:
        app.kubernetes.io/name: worker
        app.kubernetes.io/instance: authentik
    spec:
      serviceAccountName: authentik
      terminationGracePeriodSeconds: 30
      containers:
        - name: worker
          image: registry.lab.reisman.org/proxy.ghcr.io/goauthentik/server:2024.2.2
          imagePullPolicy: IfNotPresent
          args:
            - worker
          envFrom:
            - secretRef:
                name: authentik-env
          volumeMounts:
            - name: blueprints
              mountPath: /blueprints/custom
      volumes:
        - name: blueprints
          projected:
            sources:
              - secret:
                  name: authentik-blueprint-immich
              - secret:
                  name: authentik-blueprint-owncloud-android
              - secret:
                  name: authentik-blueprint-owncloud-desktop
              - secret:
                  name: authentik-blueprint-owncloud-ios
              - secret:
                  name: authentik-blueprint-owncloud-web
