---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentik-outpost-ldap
  namespace: auth
  labels:
    app.kubernetes.io/name: "authentik"
    app.kubernetes.io/instance: "authentik"
    app.kubernetes.io/component: "outpost-ldap"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: "authentik"
      app.kubernetes.io/instance: "authentik"
      app.kubernetes.io/component: "outpost-ldap"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "authentik"
        app.kubernetes.io/instance: "authentik"
        app.kubernetes.io/component: "outpost-ldap"
    spec:
      containers:
        - name: ldap
          image: registry.lab.reisman.org/proxy.ghcr.io/goauthentik/ldap
          env:
            - name: AUTHENTIK_HOST
              value: "authentik-server"
            - name: AUTHENTIK_TOKEN
              valueFrom:
                secretKeyRef:
                  name: authentik-outpost-ldap
                  key: token
            - name: AUTHENTIK_INSECURE
              value: "true"
            - name: AUTHENTIK_DEBUG
              value: "true"
          ports:
            - containerPort: 9000
              name: http
              protocol: TCP
            - containerPort: 9443
              name: https
              protocol: TCP
