apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentik-worker
  namespace: auth
  labels:
    app.kubernetes.io/name: "authentik"
    app.kubernetes.io/instance: "authentik"
    app.kubernetes.io/component: "worker"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: "authentik"
      app.kubernetes.io/instance: "authentik"
      app.kubernetes.io/component: "worker"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "authentik"
        app.kubernetes.io/instance: "authentik"
        app.kubernetes.io/component: "worker"
    spec:
      serviceAccountName: authentik
      terminationGracePeriodSeconds: 30
      containers:
        - name: worker
          image: registry.lab.reisman.org/proxy.ghcr.io/goauthentik/server:2024.2.2
          imagePullPolicy: IfNotPresent
          args:
            - worker
          envFrom:
            - secretRef:
                name: authentik-env
          #volumeMounts:
          #  - name: blueprints
          #    mountPath: /blueprints/custom
      volumes:
        - name: blueprints
          projected:
            sources:
              - secret:
                  name: authentik-blueprint-immich
              - secret:
                  name: authentik-blueprint-owncloud
