apiVersion: v1
kind: Secret
metadata:
  name: authentik-env
  namespace: auth
  labels:
    app.kubernetes.io/name: "authentik"
    app.kubernetes.io/instance: "authentik"
stringData:
  AUTHENTIK_BOOTSTRAP_EMAIL: "${vals_info_cluster_email}"
  AUTHENTIK_BOOTSTRAP_PASSWORD: "${secrets_apps_auth_authentik_bootstrapPassword}"
  AUTHENTIK_EMAIL__HOST: "mail.${vals_info_cluster_domain}"
  AUTHENTIK_EMAIL__PORT: "587"
  AUTHENTIK_EMAIL__USERNAME: "authentik@${vals_info_cluster_domain}"
  AUTHENTIK_EMAIL__PASSWORD: "${secrets_apps_auth_authentik_emailPassword}"
  AUTHENTIK_EMAIL__TIMEOUT: "30"
  AUTHENTIK_EMAIL__FROM: "authentik@${vals_info_cluster_domain}"
  AUTHENTIK_EMAIL__USE_SSL: "false"
  AUTHENTIK_EMAIL__USE_TLS: "true"
  AUTHENTIK_ERROR_REPORTING__ENABLED: "false"
  AUTHENTIK_ERROR_REPORTING__ENVIRONMENT: "k8s"
  AUTHENTIK_ERROR_REPORTING__SEND_PII: "false"
  AUTHENTIK_EVENTS__CONTEXT_PROCESSORS__ASN: "/geoip/GeoLite2-ASN.mmdb"
  AUTHENTIK_EVENTS__CONTEXT_PROCESSORS__GEOIP: "/geoip/GeoLite2-City.mmdb"
  AUTHENTIK_LOG_LEVEL: "${vals_apps_auth_authentik_logLevel:=info}"
  AUTHENTIK_OUTPOSTS__CONTAINER_IMAGE_BASE: "registry.lab.reisman.org/proxy.ghcr.io/goauthentik/%(type)s:%(version)s"
  AUTHENTIK_POSTGRESQL__HOST: "authentik-postgresql"
  AUTHENTIK_POSTGRESQL__NAME: "authentik"
  AUTHENTIK_POSTGRESQL__PASSWORD: "${secrets_apps_auth_authentik_postgresqlUserPassword}"
  AUTHENTIK_POSTGRESQL__PORT: "5432"
  AUTHENTIK_POSTGRESQL__USER: "authentik"
  AUTHENTIK_REDIS__HOST: "authentik-redis-master"
  AUTHENTIK_REDIS__PASSWORD: "${secrets_apps_auth_authentik_redisPassword}"
  AUTHENTIK_SECRET_KEY: "${secrets_apps_auth_authentik_secretKey}"
