apiVersion: v1
kind: Secret
metadata:
  name: authentik-secrets
  namespace: auth
type: Opaque
stringData:
  bootstrap-token: ${secrets_apps_auth_authentik_bootstrapToken}
  bootstrap-password: ${secrets_apps_auth_authentik_bootstrapPassword}
  email-password: ${secrets_apps_auth_authentik_emailPassword}
  redis-password: ${secrets_apps_auth_authentik_redisPassword}
  secret-key: ${secrets_apps_auth_authentik_secretKey}
