apiVersion: v1
kind: PersistentVolume
metadata:
  name: audiobookshelf-metadata-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.1.10
    path: "/mnt/main/kubernetes-nobackup/${vals_info_cluster_name}/media-audiobookshelf-metadata-pvc"
  claimRef:
    namespace: media
    name: audiobookshelf-metadata-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: audiobookshelf-metadata-pvc
  namespace: media
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
