apiVersion: v1
kind: Secret
metadata:
  name: authentik-outpost-ldap
  namespace: auth
  labels:
    app.kubernetes.io/name: authentik
    app.kubernetes.io/instance: authentik
    app.kubernetes.io/component: outpost-ldap
type: Opaque
stringData:
  token: "${secrets_apps_auth_authentik_outpost_ldap_token}"
