apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentik-worker
  namespace: auth
  labels:
    app.kubernetes.io/name: "authentik"
    app.kubernetes.io/instance: "authentik"
    app.kubernetes.io/component: "worker"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: "authentik"
      app.kubernetes.io/instance: "authentik"
      app.kubernetes.io/component: "worker"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "authentik"
        app.kubernetes.io/instance: "authentik"
        app.kubernetes.io/component: "worker"
    spec:
      serviceAccountName: authentik
      terminationGracePeriodSeconds: 30
      containers:
        - name: worker
          image: registry.lab.reisman.org/proxy.ghcr.io/goauthentik/server:2024.12.1
          imagePullPolicy: IfNotPresent
          args:
            - worker
          envFrom:
            - secretRef:
                name: authentik-env
          resources:
            requests:
              memory: "600Mi"
              cpu: "500m"
            limits:
              memory: "750Mi"
              cpu: "1"
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
            exec:
              command:
                - ak
                - healthcheck
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
            exec:
              command:
                - ak
                - healthcheck
          startupProbe:
            failureThreshold: 60
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
            exec:
              command:
                - ak
                - healthcheck
          volumeMounts:
            - name: blueprints
              mountPath: /blueprints/custom
            - name: certificate
              mountPath: /certs/auth.${vals_info_cluster_domain}
      volumes:
        - name: certificate
          secret:
            secretName: authentik-server-tls
            items:
              - key: tls.crt
                path: auth.${vals_info_cluster_domain}.crt
              - key: tls.key
                path: auth.${vals_info_cluster_domain}.key
        - name: blueprints
          projected:
            sources:
              - secret:
                  name: authentik-blueprint-dovecot
              - secret:
                  name: authentik-blueprint-grafana
              - secret:
                  name: authentik-blueprint-immich
              - secret:
                  name: authentik-blueprint-ldap
              - secret:
                  name: authentik-blueprint-paperless
              - secret:
                  name: authentik-blueprint-roundcube
