apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: libation-db-pvc
  namespace: media
spec:
  storageClassName: nfs-client-nobackup
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: libation-data-pvc
  namespace: media
spec:
  storageClassName: nfs-client-nobackup
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1000Gi
