apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cnpg-operator
  namespace: cnpg-system
spec:
  interval: 30m
  chart:
    spec:
      chart: cloudnative-pg
      version: "0.23.x"
      sourceRef:
        kind: HelmRepository
        name: cloudnative-pg
        namespace: flux-system
      interval: 1h
  values:
    image:
      repository: registry.lab.reisman.org/proxy.ghcr.io/cloudnative-pg/cloudnative-pg
    podAnnotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "8080"
