apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cnpg
  namespace: cnpg-system
spec:
  releaseName: cnpg
  chart:
    spec:
      chart: cloudnative-pg
      sourceRef:
        kind: HelmRepository
        name: cnpg
        namespace: cnpg-system
      version: "0.27.1"
      interval: 6h
  interval: 30m
  install:
    remediation:
      retries: 3
  values:
    monitoring:
      grafanaDashboard:
        create: true
