apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: postfix-spool-backup
  namespace: mail
spec:
  sourcePVC: postfix-spool
  trigger:
    schedule: "0 4 * * *"
  restic:
    pruneIntervalDays: 14
    repository: volsync-postfix-spool
    retain:
      daily: 7
      weekly: 4
      monthly: 3
    copyMethod: Direct
