apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: roundcube-postgresql
  namespace: mail
spec:
  chart:
    spec:
      chart: cluster
      sourceRef:
        kind: HelmRepository
        name: cnpg
        namespace: cnpg-system
      version: "0.6.0"
      interval: 6h
  interval: 30m
  install:
    remediation:
      retries: 3
  values:
    fullnameOverride: roundcube-postgresql
    mode: ${vals_cluster_restore_mode:=standalone}

    cluster:
      instances: 1
      enableSuperuserAccess: true
      superuserSecret: roundcube-postgresql-superuser
      storage:
        storageClass: local-path
        size: 1Gi
      initdb:
        database: roundcube
        owner: roundcube
        secret:
          name: roundcube-postgresql-appuser
      monitoring:
        enabled: true
        podMonitor:
          enabled: true

    recovery:
      method: object_store
      clusterName: roundcube-postgresql
      provider: s3
      endpointURL: "${vals_infra_backup_s3_endpoint}"
      destinationPath: "s3://${vals_infra_backup_s3_bucket_cnpg}/${vals_info_cluster_name}/roundcube/"
      s3:
        accessKey: "${secrets_infra_backup_s3_accessKey}"
        secretKey: "${secrets_infra_backup_s3_secretKey}"
      secret:
        create: true

    backups:
      enabled: true
      provider: s3
      endpointURL: "${vals_infra_backup_s3_endpoint}"
      destinationPath: "s3://${vals_infra_backup_s3_bucket_cnpg}/${vals_info_cluster_name}/roundcube/"
      s3:
        accessKey: "${secrets_infra_backup_s3_accessKey}"
        secretKey: "${secrets_infra_backup_s3_secretKey}"
      secret:
        create: true
      scheduledBackups:
        - name: daily
          schedule: "0 0 2 * * *"
          backupOwnerReference: self
          method: barmanObjectStore
      retentionPolicy: "30d"
---
apiVersion: v1
kind: Secret
metadata:
  name: roundcube-postgresql-appuser
  namespace: mail
type: kubernetes.io/basic-auth
stringData:
  username: roundcube
  password: ${secrets_apps_mail_roundcube_postgresql_app_password}
---
apiVersion: v1
kind: Secret
metadata:
  name: roundcube-postgresql-superuser
  namespace: mail
type: kubernetes.io/basic-auth
stringData:
  username: postgres
  password: ${secrets_apps_mail_roundcube_postgresql_superuser_password}
