apiVersion: v1
kind: Secret
metadata:
  name: volsync-audiobookshelf-config
  namespace: media
type: Opaque
stringData:
  RESTIC_REPOSITORY: "s3:${vals_infra_backup_s3_endpoint}/${vals_infra_backup_s3_bucket_volsync}/${vals_info_cluster_name}/media/audiobookshelf-config-pvc"
  RESTIC_PASSWORD: "${secrets_infra_backup_volsync_restic_password}"
  AWS_ACCESS_KEY_ID: "${secrets_infra_backup_s3_accessKey}"
  AWS_SECRET_ACCESS_KEY: "${secrets_infra_backup_s3_secretKey}"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: audiobookshelf-config-pvc
  namespace: media
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: audiobookshelf-config-restore
  namespace: media
spec:
  trigger:
    manual: "${vals_cluster_restore_mode}"
  restic:
    repository: volsync-audiobookshelf-config
    destinationPVC: audiobookshelf-config-pvc
    copyMethod: Direct
