apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitoring
spec:
  chart:
    spec:
      chart: grafana
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: monitoring
      version: "9.4.5"
      interval: 6h
  interval: 30m
  install:
    remediation:
      retries: 3
  values:
    extraSecretMounts:
      - name: grafana-oauth
        secretName: grafana-oauth
        defaultMode: 0440
        mountPath: /etc/secrets/oauth
        readOnly: true
    grafana.ini:
      server:
        domain: ${vals_info_cluster_domain}
        root_url: https://grafana.${vals_info_cluster_domain}
      auth:
        signout_redirect_url: "https://auth.${vals_info_cluster_domain}/application/o/grafana/end-session/"
        oauth_auto_login: true
      auth.generic_oauth:
        enabled: true
        name: authentik
        client_id: "$__file{/etc/secrets/oauth/client_id}"
        client_secret: "$__file{/etc/secrets/oauth/client_secret}"
        scopes: "openid profile email offline_access"
        auth_url: "https://auth.${vals_info_cluster_domain}/application/o/authorize/"
        token_url: "https://auth.${vals_info_cluster_domain}/application/o/token/"
        api_url: "https://auth.${vals_info_cluster_domain}/application/o/userinfo/"
        signout_redirect_url: "https://auth.${vals_info_cluster_domain}/application/o/grafana/end-session/"
        role_attribute_path: contains(groups, 'grafana-admin') && 'Admin' || contains(groups, 'grafana-editor') && 'Editor' || 'Viewer'
        auto_login: true
        use_refresh_token: true
    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
          - name: VictoriaMetrics
            type: prometheus
            access: proxy
            url: http://victoria-metrics-cluster-vmselect.monitoring.svc.cluster.local:8481/select/0/prometheus
            basicAuth: false
            isDefault: true
            editable: false
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: ${vals_infra_certManager_issuer}
      hosts:
        - grafana.${vals_info_cluster_domain}
      tls:
        - hosts:
            - "grafana.${vals_info_cluster_domain}"
          secretName: grafana-tls
      ingressClassName: nginx
    sidecar:
      dashboards:
        enabled: true
        resource: configmap
        searchNamespace:
          - ALL
    #TODO: setup smtp
