apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: victoria-metrics-agent
  namespace: monitoring
spec:
  chart:
    spec:
      chart: victoria-metrics-agent
      sourceRef:
        kind: HelmRepository
        name: victoria-metrics
        namespace: monitoring
      version: "0.26.1"
      interval: 6h
  interval: 30m
  install:
    remediation:
      retries: 3
  values:
    global:
      image:
        registry: registry.lab.reisman.org/proxy.docker.io
    annotations:
      reloader.stakater.com/auto: "true"
    configMap: victoria-metrics-agent-config
    remoteWrite:
      - url: http://victoria-metrics-cluster-vminsert.monitoring.svc.cluster.local:8480/insert/0/prometheus/api/v1/write
