apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: victoria-metrics-cluster
  namespace: monitoring
spec:
  chart:
    spec:
      chart: victoria-metrics-cluster
      sourceRef:
        kind: HelmRepository
        name: victoria-metrics
        namespace: monitoring
      version: "0.34.0"
      interval: 6h
  interval: 30m
  install:
    remediation:
      retries: 3
  values:
    vmselect: {}
    vminsert: {}
    vmstorage:
      persistentVolume:
        enabled: true
        storageClassName: nfs-client-nobackup
