apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: victoria-metrics-cluster
  namespace: monitoring
spec:
  chart:
    spec:
      chart: victoria-metrics-cluster
      sourceRef:
        kind: HelmRepository
        name: victoria-metrics
        namespace: monitoring
      version: "0.43.0"
      interval: 6h
  interval: 30m
  install:
    remediation:
      retries: 3
  values:
    vmselect:
      verticalPodAutoscaler:
        enabled: true
        updatePolicy:
          updateMode: "Off"
    vminsert:
      verticalPodAutoscaler:
        enabled: true
        updatePolicy:
          updateMode: "Off"
    vmstorage:
      verticalPodAutoscaler:
        enabled: true
        updatePolicy:
          updateMode: "Off"
      persistentVolume:
        enabled: true
        storageClassName: truenas-iscsi
