apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: victoria-metrics-operator
  namespace: monitoring
spec:
  chart:
    spec:
      chart: victoria-metrics-operator
      sourceRef:
        kind: HelmRepository
        name: victoria-metrics
        namespace: monitoring
      version: "0.44.x"
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  values:
    global:
      image:
        registry: registry.lab.reisman.org/proxy.docker.io
    logLevel: "info"
    operator:
       enable_converter_ownership: true
