apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: victoria-metrics-operator
  namespace: monitoring
spec:
  chart:
    spec:
      chart: victoria-metrics-operator
      sourceRef:
        kind: HelmRepository
        name: victoria-metrics
        namespace: monitoring
      version: "0.53.0"
      interval: 6h
  interval: 30m
  install:
    remediation:
      retries: 3
  values:
    logLevel: "info"
    operator:
       enable_converter_ownership: true
