apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: mud-server-characters-backup
  namespace: games
spec:
  sourcePVC: mud-server-characters
  trigger:
    schedule: "0 4 * * *"
  restic:
    pruneIntervalDays: 14
    repository: volsync-mud-server-characters
    retain:
      daily: 7
      weekly: 4
      monthly: 3
    copyMethod: Direct
