apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress
spec:
  releaseName: ingress-nginx
  chart:
    spec:
      chart: ingress-nginx
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: ingress
      version: '4.x'
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  values:
    controller:
      image:
        registry: registry.lab.reisman.org/proxy.registry.k8s.io
      kind: DaemonSet
      service:
        externalTrafficPolicy: Local
        loadBalancerIP: ${vals_infra_ingress_ipAddress}
        type: LoadBalancer
      extraArgs:
        default-ssl-certificate: "ingress/nginx-default-cert"
      metrics:
        enabled: true
      podAnnotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "10254"
    admissionWebhooks:
      patch:
        image:
          registry: registry.lab.reisman.org/proxy.registry.k8s.io
    defaultBackend:
      image:
        registry: registry.lab.reisman.org/proxy.registry.k8s.io
