apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress
spec:
  releaseName: ingress-nginx
  chart:
    spec:
      chart: ingress-nginx
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: ingress
      version: "4.14.1"
      interval: 6h
  interval: 30m
  install:
    remediation:
      retries: 3
  values:
    controller:
      kind: DaemonSet
      service:
        externalTrafficPolicy: Local
        loadBalancerIP: ${vals_infra_ingress_ipAddress}
        type: LoadBalancer
      extraArgs:
        default-ssl-certificate: "ingress/nginx-default-cert"
      metrics:
        enabled: true
      podAnnotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "10254"
