apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ocis-server-data
  namespace: cloud
spec:
  storageClassName: ${vals_infra_csi_nfsSubdir_backupStorageClass}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Ti
