apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: authoritative-bind-config
    namespace: dns
    files:
      - bind/named.conf
  - name: authoritative-bind-zones
    namespace: dns
    files:
      - zones/db.hobolife.org
      - zones/db.pressenter.com
      - zones/db.pressenter.net
      - zones/db.pressenter.org
      - zones/db.lab.reisman.org
      - zones/db.scobie.org
      - zones/db.xcoolgroup.org
      - zones/db.zingde.com
