apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-backup
provisioner: nfs.csi.k8s.io
parameters:
  server: 192.168.1.10
  share: /mnt/main/kubernetes
  subDir: ${vals_info_cluster_name}/$${.PVC.namespace}-$${.PVC.name}
reclaimPolicy: ${vals_infra_csi_nfsSubdir_reclaimPolicy}
volumeBindingMode: Immediate
allowVolumeExpansion: true
mountOptions:
  - nfsvers=4.1