apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-state-metrics-custom-resource-state-metrics
  namespace: monitoring
data:
  custom-resource-state-metrics.yaml: |2

    kind: CustomResourceStateMetrics
    spec:
      resources:
        - groupVersionKind:
            group: autoscaling.k8s.io
            kind: "VerticalPodAutoscaler"
            version: "v1"
          labelsFromPath:
            verticalpodautoscaler: [metadata, name]
            namespace: [metadata, namespace]
            target_api_version: [spec, targetRef, apiVersion]
            target_kind: [spec, targetRef, kind]
            target_name: [spec, targetRef, name]
          metricNamePrefix: kube_vpa
          metrics:
            # Labels
            - name: "labels"
              help: "VPA container recommendations. Kubernetes labels converted to Prometheus labels"
              each:
                type: Info
                info:
                  labelsFromPath:
                    name: [metadata, name]
            # Memory Information
            - name: "status_recommendation_containerrecommendations_target"
              help: "VPA container recommendations for memory. Target resources the VerticalPodAutoscaler recommends for the container."
              each:
                type: Gauge
                gauge:
                  path: [status, recommendation, containerRecommendations]
                  valueFrom: [target, memory]
                  labelsFromPath:
                    container: [containerName]
              commonLabels:
                resource: "memory"
                unit: "byte"
            - name: "verticalpodautoscaler_status_recommendation_containerrecommendations_lowerbound"
              help: "VPA container recommendations for memory. Minimum resources the container can use before the VerticalPodAutoscaler updater evicts it"
              each:
                type: Gauge
                gauge:
                  path: [status, recommendation, containerRecommendations]
                  valueFrom: [lowerBound, memory]
                  labelsFromPath:
                    container: [containerName]
              commonLabels:
                resource: "memory"
                unit: "byte"
            - name: "recommendations_upperbound"
              help: "VPA container recommendations for memory. Maximum resources the container can use before the VerticalPodAutoscaler updater evicts it"
              each:
                type: Gauge
                gauge:
                  path: [status, recommendation, containerRecommendations]
                  valueFrom: [upperBound, memory]
                  labelsFromPath:
                    container: [containerName]
              commonLabels:
                resource: "memory"
                unit: "byte"
            - name: "recommendations_uncappedtarget"
              help: "VPA container recommendations for memory. Target resources the VerticalPodAutoscaler recommends for the container ignoring bounds"
              each:
                type: Gauge
                gauge:
                  path: [status, recommendation, containerRecommendations]
                  valueFrom: [uncappedTarget, memory]
                  labelsFromPath:
                    container: [containerName]
              commonLabels:
                resource: "memory"
                unit: "byte"
            # CPU Information
            - name: "recommendations_target"
              help: "VPA container recommendations for cpu. Target resources the VerticalPodAutoscaler recommends for the container."
              each:
                type: Gauge
                gauge:
                  path: [status, recommendation, containerRecommendations]
                  valueFrom: [target, cpu]
                  labelsFromPath:
                    container: [containerName]
              commonLabels:
                resource: "cpu"
                unit: "core"
            - name: "recommendations_lowerbound"
              help: "VPA container recommendations for cpu. Minimum resources the container can use before the VerticalPodAutoscaler updater evicts it"
              each:
                type: Gauge
                gauge:
                  path: [status, recommendation, containerRecommendations]
                  valueFrom: [lowerBound, cpu]
                  labelsFromPath:
                    container: [containerName]
              commonLabels:
                resource: "cpu"
                unit: "core"
            - name: "recommendations_upperbound"
              help: "VPA container recommendations for cpu. Maximum resources the container can use before the VerticalPodAutoscaler updater evicts it"
              each:
                type: Gauge
                gauge:
                  path: [status, recommendation, containerRecommendations]
                  valueFrom: [upperBound, cpu]
                  labelsFromPath:
                    container: [containerName]
              commonLabels:
                resource: "cpu"
                unit: "core"
            - name: "recommendations_uncappedtarget"
              help: "VPA container recommendations for cpu. Target resources the VerticalPodAutoscaler recommends for the container ignoring bounds"
              each:
                type: Gauge
                gauge:
                  path: [status, recommendation, containerRecommendations]
                  valueFrom: [uncappedTarget, cpu]
                  labelsFromPath:
                    container: [containerName]
              commonLabels:
                resource: "cpu"
                unit: "core"
