apiVersion: v1
kind: Secret
metadata:
  name: volsync-mud-server-characters
  namespace: games
type: Opaque
stringData:
  RESTIC_REPOSITORY: "s3:${vals_infra_backup_s3_endpoint}/${vals_infra_backup_s3_bucket_volsync}/${vals_info_cluster_name}/games/mud-server-characters"
  RESTIC_PASSWORD: "${secrets_infra_backup_volsync_restic_password}"
  AWS_ACCESS_KEY_ID: "${secrets_infra_backup_s3_accessKey}"
  AWS_SECRET_ACCESS_KEY: "${secrets_infra_backup_s3_secretKey}"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mud-server-characters
  namespace: games
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: mud-server-characters-restore
  namespace: games
spec:
  trigger:
    manual: "${vals_cluster_restore_mode}"
  restic:
    repository: volsync-mud-server-characters
    destinationPVC: mud-server-characters
    copyMethod: Direct
