apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: paperless-redis
  namespace: paperless
spec:
  interval: 5m
  timeout: 30m
  chart:
    spec:
      chart: bitnamicharts/redis
      version: "18.19.4"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    global:
      imageRegistry: registry.lab.reisman.org/proxy.docker.io
    architecture: standalone
    auth:
      existingSecret: paperless-secrets
      existingSecretPasswordKey: redis-password
    master:
      persistence:
        enabled: false
        storageClass: ${vals_infra_csi_nfsSubdir_backupStorageClass}
    metrics:
      enabled: true
