apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: paperless-postgresql
  namespace: paperless
spec:
  instances: 1

  # Moderate autovacuum tuning for celery workloads
  postgresql:
    parameters:
      autovacuum_naptime: "45s"
      autovacuum_vacuum_scale_factor: "0.1"
      autovacuum_analyze_scale_factor: "0.05"

      # Performance
      shared_buffers: "192MB"
      effective_cache_size: "4GB"
      maintenance_work_mem: "96MB"
      checkpoint_completion_target: "0.9"

  superuserSecret:
    name: paperless-postgresql-superuser

  bootstrap:
    initdb:
      database: paperless
      owner: paperless
      secret:
        name: paperless-postgresql-appuser

  backup:
    barmanObjectStore:
      destinationPath: "s3://backup/${vals_info_cluster_name}/cnpg/paperless-postgresql/"
      endpointURL: "http://${vals_infra_storage_truenasCsi_nfsServer}:30157"
      s3Credentials:
        accessKeyId:
          name: cnpg-backup-credentials
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: cnpg-backup-credentials
          key: SECRET_ACCESS_KEY
      wal:
        compression: gzip
    retentionPolicy: "30d"

  storage:
    storageClass: truenas-iscsi
    size: 1Gi
---
apiVersion: v1
kind: Secret
metadata:
  name: cnpg-backup-credentials
  namespace: paperless
type: Opaque
stringData:
  ACCESS_KEY_ID: "${secrets_infra_storage_backup_awsAccessKeyId}"
  SECRET_ACCESS_KEY: "${secrets_infra_storage_backup_awsSecretAccessKey}"
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: paperless-postgresql-backup
  namespace: paperless
spec:
  suspend: ${vals_infra_storage_backup_paused}
  schedule: "0 3 * * *"
  backupOwnerReference: self
  cluster:
    name: paperless-postgresql
---
apiVersion: v1
kind: Secret
metadata:
  name: paperless-postgresql-appuser
  namespace: paperless
type: kubernetes.io/basic-auth
stringData:
  username: paperless
  password: ${secrets_apps_paperless_paperless_postgresql_app_password}
---
apiVersion: v1
kind: Secret
metadata:
  name: paperless-postgresql-superuser
  namespace: paperless
type: kubernetes.io/basic-auth
stringData:
  username: postgres
  password: ${secrets_apps_paperless_paperless_postgresql_superuser_password}
