apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-server-media
  namespace: paperless
spec:
  storageClassName: truenas-nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ti
