apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: paperless-redis
  namespace: paperless
spec:
  interval: 5m
  timeout: 30m
  chart:
    spec:
      chart: bitnamicharts/redis
      version: "18.x"
      sourceRef:
        kind: HelmRepository
        name: registry-lab
        namespace: flux-system
  values:
    architecture: standalone
    auth:
      existingSecret: paperless-secrets
      existingSecretPasswordKey: redis-password
    image:
      registry: registry.lab.reisman.org/proxy.docker.io
    master:
      persistence:
        enabled: false
        storageClass: ${vals_infra_csi_nfsSubdir_backupStorageClass}
    metrics:
      enabled: true
      image:
        registry: registry.lab.reisman.org/proxy.docker.io
