apiVersion: v1
kind: Secret
metadata:
  name: paperless-secrets
  namespace: paperless
type: Opaque
stringData:
  secret-key: ${secrets_apps_paperless_paperless_secretKey}
  oidc-config: |
    {
        "openid_connect": {
            "APPS": [
                {
                    "provider_id": "authentik",
                    "name": "Login",
                    "client_id": "${secrets_apps_auth_applications_paperless_clientId}",
                    "secret": "${secrets_apps_auth_applications_paperless_clientSecret}",
                    "settings": {
                        "server_url": "https://auth.${vals_info_cluster_domain}/application/o/paperless/.well-known/openid-configuration"
                    }
                }
            ],
            "OAUTH_PKCE_ENABLED": "True"
        }
    }
