apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: paperless-postgresql
  namespace: paperless
spec:
  interval: 5m
  timeout: 30m
  chart:
    spec:
      chart: bitnamicharts/postgresql
      version: "16.7.27"
      sourceRef:
        kind: HelmRepository
        name: dockerio
        namespace: flux-system
  values:
    global:
      imageRegistry: registry.lab.reisman.org/proxy.docker.io
    architecture: standalone
    primary:
      persistence:
        storageClass: nfs-client-ssd
      resourcesPreset: "${vals_apps_paperless_paperless_postgresql_resourcesPreset:=small}"
      startupProbe:
        enabled: true
        failureThreshold: 150
      nodeSelector:
        homelab.local/vm-host: hobbes
    auth:
      database: paperless
      username: paperless
      existingSecret: paperless-secrets
      secretKeys:
        adminPasswordKey: postgresql-admin-password
        userPasswordKey: postgresql-user-password
      usePasswordFiles: false
    backup:
      enabled: true
      cronjob:
        storage:
          storageClass: ${vals_infra_csi_nfsSubdir_backupStorageClass}
    metrics:
      enabled: true
