apiVersion: autoscaling.k8s.io/v1beta2
kind: VerticalPodAutoscaler
metadata:
  name: paperless-gotenberg-vpa
  namespace: paperless
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: paperless-gotenberg
  updatePolicy:
    updateMode: "Off"
