apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: paperless-tika
  namespace: paperless
spec:
  interval: 5m
  chart:
    spec:
      chart: tika
      version: "2.9.x"
      sourceRef:
        kind: HelmRepository
        name: paperless-tika
        namespace: paperless
  values:
    image:
      repository: registry.lab.reisman.org/proxy.docker.io/apache/tika
