apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: paperless-tika
  namespace: paperless
spec:
  chart:
    spec:
      chart: tika
      version: "3.2.2"
      sourceRef:
        kind: HelmRepository
        name: paperless-tika
        namespace: paperless
      interval: 6h
  interval: 30m
