#TODO this is not working
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging-dns
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: ${vals_info_cluster_email}
    privateKeySecretRef:
      name: letsencrypt-staging-dns
    solvers:
    - dns01:
        rfc2136:
          #TODO Should we template in the nameserver?
          nameserver: ns1.reisman.org
          tsigKeyName: letsencrypt
          tsigAlgorithm: HMACSHA512
          tsigSecretSecretRef:
            name: letsencrypt-dns
            key: key
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production-dns
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: ${vals_info_cluster_email}
    privateKeySecretRef:
      name: letsencrypt-production-dns
    solvers:
    - dns01:
        rfc2136:
          #TODO Should we template in the nameserver?
          nameserver: ns1.reisman.org
          tsigKeyName: letsencrypt
          tsigAlgorithm: HMACSHA512
          tsigSecretSecretRef:
            name: letsencrypt-dns
            key: key
---
apiVersion: v1
kind: Secret
metadata:
  name: letsencrypt-dns
  namespace: cert-manager
type: Opaque
stringData:
  key: ${secrets_apps_dns_authoritative_letsencryptKey}
