apiVersion: operator.victoriametrics.com/v1beta1
kind: VMPodScrape
metadata:
  name: envoy-proxy
  namespace: ingress
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: envoy
      app.kubernetes.io/component: proxy
  podMetricsEndpoints:
    - port: metrics
      path: /stats/prometheus
