apiVersion: v1
kind: Secret
metadata:
  name: authentik-blueprint-immich
  namespace: auth
type: Opaque
stringData:
  immich.yaml: |
    # yaml-language-server: $schema=https://goauthentik.io/blueprints/schema.json
    version: 1
    metadata:
        name: custom-immich
    entries:
      - model: authentik_providers_oauth2.oauth2provider
        id: immich
        identifiers:
          name: immich
        state: present
        attrs:
          authentication_flow: !Find [authentik_flows.flow, [slug, default-authentication-flow]]
          authorization_flow: !Find [authentik_flows.flow, [slug, default-provider-authorization-explicit-consent]]
          client_type: confidential
          client_id: ${secrets_apps_auth_applications_immich_clientId}
          client_secret: ${secrets_apps_auth_applications_immich_clientSecret}
          redirect_uris: |
            https://photos.${vals_info_cluster_domain}/auth/login
            https://photos.${vals_info_cluster_domain}/user-settings
            app.immich:/
          access_code_validity: minutes=1
          access_token_validity: minutes=5
          signing_key: !Find [authentik_crypto.CertificateKeyPair, [name, authentik Self-signed Certificate]]
          property_mappings:
            - !Find [authentik_providers_oauth2.ScopeMapping, [scope_name, email]]
            - !Find [authentik_providers_oauth2.ScopeMapping, [scope_name, openid]]
            - !Find [authentik_providers_oauth2.ScopeMapping, [scope_name, profile]]

      - model: authentik_core.application
        identifiers:
          slug: immich
        state: present
        attrs:
          name: immich
          slug: immich
          provider: !KeyOf immich
          meta_launch_url: https://photos.${vals_info_cluster_domain}/
          policy_engine_mode: any

      - model: authentik_core.group
        id: immich
        identifiers:
          name: immich
        state: present
        attrs:
          name: immich
          parent: null
      
      - model: authentik_policies.PolicyBinding
        id: immich-policy-binding
        identifiers:
          order: 10
        attrs:
          order: 10
          group: !KeyOf immich
          target: !Find [authentik_core.Application, [slug, immich]]
