apiVersion: v1
kind: Secret
metadata:
  name: authentik-blueprint-owncloud
  namespace: auth
type: Opaque
stringData:
  owncloud-web.yaml: |
    # yaml-language-server: $schema=https://goauthentik.io/blueprints/schema.json
    version: 1
    metadata:
        name: Custom - Owncloud
    entries:

      # Groups
      - model: authentik_core.group
        id: owncloud
        identifiers:
          name: owncloud
        state: present
        attrs:
          name: owncloud
          parent: null
      - model: authentik_core.group
        id: owncloud-admins
        identifiers:
          name: owncloud-admins
        state: present
        attrs:
          name: owncloud-admins
          parent: !Find [authentik_core.group, [name, owncloud]]
      - model: authentik_core.group
        id: owncloud-users
        identifiers:
          name: owncloud-users
        state: present
        attrs:
          name: owncloud-users
          parent: !Find [authentik_core.group, [name, owncloud]]

      # Website
      - model: authentik_providers_oauth2.oauth2provider
        id: owncloud-web
        identifiers:
          name: owncloud-web
        state: present
        attrs:
          authentication_flow: !Find [authentik_flows.flow, [slug, default-authentication-flow]]
          authorization_flow: !Find [authentik_flows.flow, [slug, default-provider-authorization-explicit-consent]]
          client_type: public
          client_id: ${secrets_apps_auth_applications_owncloud_clientId}
          redirect_uris: |
            https://cloud.${vals_info_cluster_domain}/
            https://cloud.${vals_info_cluster_domain}/oidc-callback.html
            https://cloud.${vals_info_cluster_domain}/oidc-silent-redirect.html
          access_code_validity: minutes=1
          access_token_validity: minutes=5
          signing_key: !Find [authentik_crypto.CertificateKeyPair, [name, authentik Self-signed Certificate]]
          property_mappings:
            - !Find [authentik_providers_oauth2.ScopeMapping, [scope_name, email]]
            - !Find [authentik_providers_oauth2.ScopeMapping, [scope_name, openid]]
            - !Find [authentik_providers_oauth2.ScopeMapping, [scope_name, profile]]
      - model: authentik_core.application
        identifiers:
          slug: owncloud-web
        state: present
        attrs:
          name: owncloud-web
          slug: owncloud-web
          provider: !KeyOf owncloud-web
          meta_launch_url: https://cloud.${vals_info_cluster_domain}/
          policy_engine_mode: any
      - model: authentik_policies.PolicyBinding
        id: owncloud-web-policy-binding
        identifiers:
          name: owncloud-web-policy-binding
          order: 10
        attrs:
          order: 10
          group: !Find [authentik_core.group, [name, owncloud]]
          target: !Find [authentik_core.Application, [slug, owncloud-web]]

      # Desktop Client
      - model: authentik_providers_oauth2.oauth2provider
        id: owncloud-desktop
        identifiers:
          name: owncloud-desktop
        state: present
        attrs:
          authentication_flow: !Find [authentik_flows.flow, [slug, default-authentication-flow]]
          authorization_flow: !Find [authentik_flows.flow, [slug, default-provider-authorization-explicit-consent]]
          client_type: confidential
          client_id: ${secrets_apps_auth_applications_owncloudDesktop_clientId}
          client_secret: ${secrets_apps_auth_applications_owncloudDesktop_clientSecret}
          redirect_uris: |
            http://127.0.0.1(:.*)?
            http://localhost(:.*)?
          access_code_validity: minutes=1
          access_token_validity: minutes=5
          signing_key: !Find [authentik_crypto.CertificateKeyPair, [name, authentik Self-signed Certificate]]
          property_mappings:
            - !Find [authentik_providers_oauth2.ScopeMapping, [scope_name, email]]
            - !Find [authentik_providers_oauth2.ScopeMapping, [scope_name, openid]]
            - !Find [authentik_providers_oauth2.ScopeMapping, [scope_name, profile]]
      - model: authentik_core.application
        identifiers:
          slug: owncloud-desktop
        state: present
        attrs:
          name: owncloud-desktop
          slug: owncloud-desktop
          provider: !KeyOf owncloud-desktop
          meta_launch_url: blank://blank
          policy_engine_mode: any
      - model: authentik_policies.PolicyBinding
        id: owncloud-desktop-policy-binding
        identifiers:
          name: owncloud-desktop-policy-binding
          order: 10
        attrs:
          order: 10
          group: !Find [authentik_core.group, [name, owncloud]]
          target: !Find [authentik_core.Application, [slug, owncloud-desktop]]

      # Android Client
      - model: authentik_providers_oauth2.oauth2provider
        id: owncloud-android
        identifiers:
          name: owncloud-android
        state: present
        attrs:
          authentication_flow: !Find [authentik_flows.flow, [slug, default-authentication-flow]]
          authorization_flow: !Find [authentik_flows.flow, [slug, default-provider-authorization-explicit-consent]]
          client_type: confidential
          client_id: ${secrets_apps_auth_applications_owncloudAndroid_clientId}
          client_secret: ${secrets_apps_auth_applications_owncloudAndroid_clientSecret}
          redirect_uris: |
            oc://android.owncloud.com
          access_code_validity: minutes=1
          access_token_validity: minutes=5
          signing_key: !Find [authentik_crypto.CertificateKeyPair, [name, authentik Self-signed Certificate]]
          property_mappings:
            - !Find [authentik_providers_oauth2.ScopeMapping, [scope_name, email]]
            - !Find [authentik_providers_oauth2.ScopeMapping, [scope_name, openid]]
            - !Find [authentik_providers_oauth2.ScopeMapping, [scope_name, profile]]
      - model: authentik_core.application
        identifiers:
          slug: owncloud-android
        state: present
        attrs:
          name: owncloud-android
          slug: owncloud-android
          provider: !KeyOf owncloud-android
          meta_launch_url: blank://blank
          policy_engine_mode: any
      - model: authentik_policies.PolicyBinding
        id: owncloud-android-policy-binding
        identifiers:
          name: owncloud-android-policy-binding
          order: 10
        attrs:
          order: 10
          group: !Find [authentik_core.group, [name, owncloud]]
          target: !Find [authentik_core.Application, [slug, owncloud-android]]

      # iOS Client
      - model: authentik_providers_oauth2.oauth2provider
        id: owncloud-ios
        identifiers:
          name: owncloud-ios
        state: present
        attrs:
          authentication_flow: !Find [authentik_flows.flow, [slug, default-authentication-flow]]
          authorization_flow: !Find [authentik_flows.flow, [slug, default-provider-authorization-explicit-consent]]
          client_type: confidential
          client_id: ${secrets_apps_auth_applications_owncloudIos_clientId}
          client_secret: ${secrets_apps_auth_applications_owncloudIos_clientSecret}
          redirect_uris: |
            oc://ios.owncloud.com
            oc.ios://ios.owncloud.com
          access_code_validity: minutes=1
          access_token_validity: minutes=5
          signing_key: !Find [authentik_crypto.CertificateKeyPair, [name, authentik Self-signed Certificate]]
          property_mappings:
            - !Find [authentik_providers_oauth2.ScopeMapping, [scope_name, email]]
            - !Find [authentik_providers_oauth2.ScopeMapping, [scope_name, openid]]
            - !Find [authentik_providers_oauth2.ScopeMapping, [scope_name, profile]]
      - model: authentik_core.application
        identifiers:
          slug: owncloud-ios
        state: present
        attrs:
          name: owncloud-ios
          slug: owncloud-ios
          provider: !KeyOf owncloud-ios
          meta_launch_url: blank://blank
          policy_engine_mode: any
      - model: authentik_policies.PolicyBinding
        id: owncloud-ios-policy-binding
        identifiers:
          name: owncloud-ios-policy-binding
          order: 10
        attrs:
          order: 10
          group: !Find [authentik_core.group, [name, owncloud]]
          target: !Find [authentik_core.Application, [slug, owncloud-ios]]
