apiVersion: v1
kind: Secret
metadata:
  name: authentik-blueprint-owncloud-ios
  namespace: auth
type: Opaque
stringData:
  owncloud-ios.yaml: |
    # yaml-language-server: $schema=https://goauthentik.io/blueprints/schema.json
    version: 1
    metadata:
        name: owncloud-ios
    entries:
      - model: authentik_providers_oauth2.oauth2provider
        id: owncloud-ios
        identifiers:
          name: owncloud-ios
        state: present
        attrs:
          authentication_flow: !Find [authentik_flows.flow, [slug, default-authentication-flow]]
          authorization_flow: !Find [authentik_flows.flow, [slug, default-provider-authorization-explicit-consent]]
          client_type: confidential
          client_id: ${secrets_apps_auth_applications_owncloudIos_clientId}
          client_secret: ${secrets_apps_auth_applications_owncloudIos_clientSecret}
          redirect_uris: |
            oc://ios.owncloud.com
            oc.ios://ios.owncloud.com
          access_code_validity: minutes=1
          access_token_validity: minutes=5
          signing_key: !Find [authentik_crypto.CertificateKeyPair, [name, authentik Self-signed Certificate]]
          property_mappings:
            - !Find [authentik_providers_oauth2.ScopeMapping, [scope_name, email]]
            - !Find [authentik_providers_oauth2.ScopeMapping, [scope_name, openid]]
            - !Find [authentik_providers_oauth2.ScopeMapping, [scope_name, profile]]

      - model: authentik_core.application
        identifiers:
          slug: owncloud-ios
        state: present
        attrs:
          name: owncloud-ios
          slug: owncloud-ios
          provider: !KeyOf owncloud-ios
          meta_launch_url: blank://blank
          policy_engine_mode: any
