apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: dragonfly
  namespace: flux-system
spec:
  type: "oci"
  url: oci://ghcr.io/dragonflydb/dragonfly/helm
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: dragonfly-operator
  namespace: flux-system
spec:
  type: "oci"
  url: oci://ghcr.io/dragonflydb/dragonfly-operator/helm
