apiVersion: autoscaling.k8s.io/v1beta2
kind: VerticalPodAutoscaler
metadata:
  name: postfix-server-vpa
  namespace: mail
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: postfix-server
  updatePolicy:
    updateMode: "Off"
