apiVersion: v1
kind: Secret
metadata:
  name: roundcube-secrets
  namespace: mail
type: Opaque
stringData:
  postgresql-admin-password: ${secrets_apps_mail_roundcube_postgresqlAdminPassword}
  postgresql-user-password: ${secrets_apps_mail_roundcube_postgresqlUserPassword}
  des-key: ${secrets_apps_mail_roundcube_desKey}
  #redis-password: ${secrets_apps_mail_roundcube_redisPassword}
