apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rspamd-var
  namespace: mail
spec:
  storageClassName: nfs-client-nobackup
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
