apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: audiobookshelf-config-pvc
  namespace: media
spec:
  storageClassName: ${vals_infra_csi_nfsSubdir_backupStorageClass}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: audiobookshelf-metadata-pvc
  namespace: media
spec:
  storageClassName: nfs-client-nobackup
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
