apiVersion: v1
kind: Secret
metadata:
  name: jellyfin-sso-config
  namespace: media
type: Opaque
stringData:
  SSO-Auth.xml: |
    <?xml version="1.0" encoding="utf-8"?>
    <PluginConfiguration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <OidConfigs>
        <OidConfig>
          <OidProviderName>authentik</OidProviderName>
          <OidEndpoint>https://auth.${vals_info_cluster_domain}/application/o/jellyfin/.well-known/openid-configuration</OidEndpoint>
          <OidClientId>${secrets_apps_auth_applications_jellyfin_clientId}</OidClientId>
          <OidSecret>${secrets_apps_auth_applications_jellyfin_clientSecret}</OidSecret>
          <Enabled>true</Enabled>
          <EnableAuthorization>true</EnableAuthorization>
          <EnableAllFolders>true</EnableAllFolders>
          <EnabledFolders />
          <AdminRoles>
            <string>jellyfin-admin</string>
          </AdminRoles>
          <Roles>
            <string>jellyfin</string>
          </Roles>
          <EnableFolderRoles>false</EnableFolderRoles>
          <FolderRoleMappings />
          <RoleClaim>groups</RoleClaim>
          <OidScopes>["openid", "profile", "email"]</OidScopes>
          <DisableHttps>false</DisableHttps>
          <DoNotValidateEndpoints>false</DoNotValidateEndpoints>
          <DoNotValidateIssuerName>false</DoNotValidateIssuerName>
        </OidConfig>
      </OidConfigs>
      <SamlConfigs />
    </PluginConfiguration>
