apiVersion: batch/v1
kind: CronJob
metadata:
  name: libation
  namespace: media
spec:
  schedule: "0 0 * * 0"
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 5
  successfulJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          securityContext:
            runAsUser: 1001
            runAsGroup: 1001
          restartPolicy: Never
          containers:
          - name: libation
            image: docker.io/rmcrackan/libation:13.1.8
            imagePullPolicy: Always
            volumeMounts:
            - name: data
              mountPath: /data
            - name: settings
              mountPath: /config/Settings.json
              subPath: "Settings.json"
            - name: accounts
              mountPath: /config/AccountsSettings.json
              subPath: "AccountsSettings.json"
            - name: db-local
              mountPath: /db
            - name: tmp
              mountPath: /tmp
            # Mount over the script the image actually executes:
            - name: liberate-script
              mountPath: /libation/liberate.sh
              subPath: liberate.sh
          volumes:
          - name: settings
            configMap:
              name: libation-settings
          - name: accounts
            secret:
              secretName: libation-accounts
          - name: data
            persistentVolumeClaim:
              claimName: audible-pvc
          - name: db-local
            emptyDir: {}
          - name: tmp
            emptyDir: {}
          - name: liberate-script
            configMap:
              name: libation-liberate-script
              defaultMode: 0755
