apiVersion: batch/v1
kind: CronJob
metadata:
  name: libation
  namespace: media
spec:
  schedule: "0 0 * * 0"
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 5
  successfulJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          securityContext:
            runAsUser: 1001
            runAsGroup: 1001
          restartPolicy: Never
          containers:
          - name: libation
            image: docker.io/rmcrackan/libation:13.1.8
            imagePullPolicy: Always
            env:
            - name: LIBATION_BOOKS_DIR
              value: /data
            - name: LIBATION_CONFIG_DIR
              value: /config
            - name: LIBATION_DB_DIR
              value: /db
            command: ["/bin/sh", "-lc"]
            args:
              - |
                set -euo pipefail
                /liberate.sh
            volumeMounts:
            - name: data
              mountPath: /data
            - name: settings
              mountPath: /config/Settings.json
              subPath: "Settings.json"
            - name: accounts
              mountPath: /config/AccountsSettings.json
              subPath: "AccountsSettings.json"
            - name: db-local
              mountPath: /db
            - name: tmp
              mountPath: /tmp
            - name: liberate-script
              mountPath: /liberate.sh
              subPath: liberate.sh
          volumes:
          - name: settings
            configMap:
              name: libation-settings
          - name: accounts
            secret:
              secretName: libation-accounts
          - name: data
            persistentVolumeClaim:
              claimName: audiobooks-pvc
          - name: db-local
            emptyDir: {}
          - name: tmp
            emptyDir: {}
          - name: liberate-script
            configMap:
              name: libation-liberate-script
              defaultMode: 0755
