apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: audible-pvc
  namespace: media
spec:
  storageClassName: nfs-client-nobackup
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1000Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: audiobooks-pvc
  namespace: media
spec:
  storageClassName: nfs-client-nobackup
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1000Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebooks-pvc
  namespace: media
spec:
  storageClassName: nfs-client-nobackup
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1000Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: movies-pvc
  namespace: media
spec:
  storageClassName: nfs-client-nobackup
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1000Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tv-pvc
  namespace: media
spec:
  storageClassName: nfs-client-nobackup
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1000Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: music-pvc
  namespace: media
spec:
  storageClassName: nfs-client-nobackup
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1000Gi
