apiVersion: v1
kind: PersistentVolume
metadata:
  name: audible-pv
spec:
  capacity:
    storage: 1000Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.1.10
    path: /mnt/main/media/audible
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: audible-pvc
  namespace: media
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1000Gi
  volumeName: audible-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: audiobooks-pv
spec:
  capacity:
    storage: 1000Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.1.10
    path: /mnt/main/media/audiobooks
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: audiobooks-pvc
  namespace: media
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1000Gi
  volumeName: audiobooks-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ebooks-pv
spec:
  capacity:
    storage: 1000Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.1.10
    path: /mnt/main/media/ebooks
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebooks-pvc
  namespace: media
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1000Gi
  volumeName: ebooks-pv
