apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: truenas-iscsi
provisioner: csi.truenas.io
parameters:
  protocol: "iscsi"
  pool: "ssd"
  datasetPath: "k8s-test/${vals_info_cluster_name}"
  compression: "LZ4"
  volblocksize: "16K"
  iscsi.blocksize: "4096"
reclaimPolicy: Retain
volumeBindingMode: Immediate
allowVolumeExpansion: true
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: truenas-nfs
provisioner: csi.truenas.io
parameters:
  protocol: "nfs"
  pool: "main"
  datasetPath: "k8s-test/${vals_info_cluster_name}"
  compression: "LZ4"
reclaimPolicy: Retain
volumeBindingMode: Immediate
allowVolumeExpansion: true
