---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentik-outpost-ldap
  namespace: auth
  labels:
    app.kubernetes.io/name: "authentik"
    app.kubernetes.io/instance: "authentik"
    app.kubernetes.io/component: "outpost-ldap"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: "authentik"
      app.kubernetes.io/instance: "authentik"
      app.kubernetes.io/component: "outpost-ldap"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "authentik"
        app.kubernetes.io/instance: "authentik"
        app.kubernetes.io/component: "outpost-ldap"
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9300"
    spec:
      containers:
        - name: ldap
          image: registry.lab.reisman.org/proxy.ghcr.io/goauthentik/ldap:2024.8.3
          env:
            - name: AUTHENTIK_HOST
              value: "http://authentik-server"
            - name: AUTHENTIK_TOKEN
              valueFrom:
                secretKeyRef:
                  name: authentik-outpost-ldap
                  key: token
            - name: AUTHENTIK_INSECURE
              value: "false"
            - name: AUTHENTIK_DEBUG
              value: "true"
          ports:
            - name: ldap
              containerPort: 3389
              protocol: TCP
            - name: ldaps
              containerPort: 6636
              protocol: TCP
            - name: metrics
              containerPort: 9300
              protocol: TCP
            - name: debug
              containerPort: 9900
              protocol: TCP
