apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentik-worker
  namespace: auth
  labels:
    app.kubernetes.io/name: "authentik"
    app.kubernetes.io/instance: "authentik"
    app.kubernetes.io/component: "worker"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: "authentik"
      app.kubernetes.io/instance: "authentik"
      app.kubernetes.io/component: "worker"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "authentik"
        app.kubernetes.io/instance: "authentik"
        app.kubernetes.io/component: "worker"
    spec:
      serviceAccountName: authentik
      terminationGracePeriodSeconds: 30
      containers:
        - name: worker
          image: registry.lab.reisman.org/proxy.ghcr.io/goauthentik/server:2024.8.3
          imagePullPolicy: IfNotPresent
          args:
            - worker
          envFrom:
            - secretRef:
                name: authentik-env
          volumeMounts:
            - name: blueprints
              mountPath: /blueprints/custom
            - name: certificate
              mountPath: /certs/auth.${vals_info_cluster_domain}
      volumes:
        - name: certificate
          secret:
            secretName: authentik-server-tls
            items:
              - key: tls.crt
                path: auth.${vals_info_cluster_domain}.crt
              - key: tls.key
                path: auth.${vals_info_cluster_domain}.key
        - name: blueprints
          secret:
            secretName: authentik-blueprints
