apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: authentik-postgresql
  namespace: auth
spec:
  instances: 1

  superuserSecret:
    name: authentik-postgresql-superuser

  bootstrap:
    initdb:
      database: authentik
      owner: authentik
      secret:
        name: authentik-postgresql-appuser

  resources:
    requests:
      memory: "512Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"

  probes:
    liveness:
      isolationCheck:
        enabled: true
        connectionTimeout: 5000
        requestTimeout: 5000

  backup:
    barmanObjectStore:
      destinationPath: "s3://backup/${vals_info_cluster_name}/cnpg/authentik-postgresql/"
      endpointURL: "http://${vals_infra_storage_truenasCsi_nfsServer}:30157"
      s3Credentials:
        accessKeyId:
          name: cnpg-backup-credentials
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: cnpg-backup-credentials
          key: SECRET_ACCESS_KEY
      wal:
        compression: gzip
    retentionPolicy: "30d"

  storage:
    storageClass: truenas-iscsi
    size: 5Gi

  # Enable monitoring
  monitoring:
    enablePodMonitor: true
---
apiVersion: v1
kind: Secret
metadata:
  name: cnpg-backup-credentials
  namespace: auth
type: Opaque
stringData:
  ACCESS_KEY_ID: "${secrets_infra_storage_backup_awsAccessKeyId}"
  SECRET_ACCESS_KEY: "${secrets_infra_storage_backup_awsSecretAccessKey}"
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: authentik-postgresql-backup
  namespace: auth
spec:
  suspend: ${vals_infra_storage_backup_paused}
  schedule: "0 3 * * *"
  backupOwnerReference: self
  cluster:
    name: authentik-postgresql
---
apiVersion: v1
kind: Secret
metadata:
  name: authentik-postgresql-appuser
  namespace: auth
type: kubernetes.io/basic-auth
stringData:
  username: authentik
  password: ${secrets_apps_auth_authentik_postgresql_app_password}
---
apiVersion: v1
kind: Secret
metadata:
  name: authentik-postgresql-superuser
  namespace: auth
type: kubernetes.io/basic-auth
stringData:
  username: postgres
  password: ${secrets_apps_auth_authentik_postgresql_superuser_password}
