apiVersion: operator.victoriametrics.com/v1beta1
kind: VMPodScrape
metadata:
  name: authentik-server
  namespace: auth
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: authentik
      app.kubernetes.io/instance: authentik
      app.kubernetes.io/component: server
  podMetricsEndpoints:
    - targetPort: 9300
