apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: authentik-postgresql
  namespace: auth
spec:
  instances: 1

  # Tune PostgreSQL for high-write workload
  postgresql:
    parameters:
      # Autovacuum - more aggressive for high-churn tables
      autovacuum_max_workers: "3"
      autovacuum_naptime: "30s"
      autovacuum_vacuum_threshold: "25"
      autovacuum_analyze_threshold: "25"
      autovacuum_vacuum_scale_factor: "0.05"
      autovacuum_analyze_scale_factor: "0.05"
      autovacuum_vacuum_cost_delay: "10ms"
      autovacuum_vacuum_cost_limit: "1000"

      # Performance - tuned for NFS-backed storage
      shared_buffers: "256MB"
      effective_cache_size: "4GB"
      maintenance_work_mem: "128MB"
      checkpoint_completion_target: "0.9"
      wal_buffers: "4MB"
      max_wal_size: "2GB"
      wal_keep_size: "256MB"
      max_connections: "100"
      synchronous_commit: "off"

  superuserSecret:
    name: authentik-postgresql-superuser

  bootstrap:
    initdb:
      database: authentik
      owner: authentik
      secret:
        name: authentik-postgresql-appuser
      postInitSQL:
        # Per-table autovacuum tuning for highest-churn tables
        - ALTER TABLE django_channels_postgres_message SET (autovacuum_vacuum_scale_factor = 0.01, autovacuum_vacuum_threshold = 100);
        - ALTER TABLE django_postgres_cache_cacheentry SET (autovacuum_vacuum_scale_factor = 0.01);
        - ALTER TABLE authentik_tasks_task SET (autovacuum_vacuum_scale_factor = 0.01);
        - ALTER TABLE authentik_tasks_tasklog SET (autovacuum_vacuum_scale_factor = 0.01);
        - ALTER TABLE authentik_core_session SET (autovacuum_vacuum_scale_factor = 0.05);

  resources:
    requests:
      memory: "512Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"

  probes:
    liveness:
      isolationCheck:
        enabled: true
        connectionTimeout: 5000
        requestTimeout: 5000

  storage:
    storageClass: nfs-client-ssd
    size: 2Gi

  # Enable monitoring
  monitoring:
    enablePodMonitor: true
---
apiVersion: v1
kind: Secret
metadata:
  name: authentik-postgresql-appuser
  namespace: auth
type: kubernetes.io/basic-auth
stringData:
  username: authentik
  password: ${secrets_apps_auth_authentik_postgresql_app_password}
---
apiVersion: v1
kind: Secret
metadata:
  name: authentik-postgresql-superuser
  namespace: auth
type: kubernetes.io/basic-auth
stringData:
  username: postgres
  password: ${secrets_apps_auth_authentik_postgresql_superuser_password}
