apiVersion: operator.victoriametrics.com/v1beta1
kind: VMPodScrape
metadata:
  name: mapmaker-server
  namespace: http
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: server
      app.kubernetes.io/instance: mapmaker
  podMetricsEndpoints:
    - targetPort: 8080
