apiVersion: autoscaling.k8s.io/v1beta2
kind: VerticalPodAutoscaler
metadata:
  name: rssreader-server-vpa
  namespace: http
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: rssreader-server
  updatePolicy:
    updateMode: "Off"
