apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: http-server-tls
  namespace: http
spec:
  secretName: http-server-tls
  dnsNames:
    - ${vals_info_cluster_domain}
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: ${vals_infra_certManager_issuer}
