apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rssreader-server
  namespace: http
  labels:
    app.kubernetes.io/name: "rssreader"
    app.kubernetes.io/instance: "rssreader"
    app.kubernetes.io/component: "server"
  annotations:
    cert-manager.io/cluster-issuer: ${vals_infra_certManager_issuer}
spec:
  ingressClassName: nginx
  tls:
    - hosts:
      - "rssreader.${vals_info_cluster_domain}"
      secretName: rssreader-server-tls
  rules:
    - host: "rssreader.${vals_info_cluster_domain}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: rssreader-server
                port:
                  name: http
