apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-server-data
  namespace: paperless
spec:
  storageClassName: ${vals_infra_csi_nfsSubdir_backupStorageClass}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-server-media
  namespace: paperless
spec:
  storageClassName: ${vals_infra_csi_nfsSubdir_backupStorageClass}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Ti
