apiVersion: v1
kind: Secret
metadata:
  name: paperless-secrets
  namespace: paperless
type: Opaque
stringData:
  postgresql-admin-password: ${secrets_apps_paperless_paperless_postgresqlAdminPassword}
  postgresql-user-password: ${secrets_apps_paperless_paperless_postgresqlUserPassword}
  redis-password: ${secrets_apps_paperless_paperless_redisPassword}
