apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: paperless-postgresql
  namespace: paperless
spec:
  interval: 5m
  chart:
    spec:
      chart: bitnamicharts/postgresql
      version: '15.x'
      sourceRef:
        kind: HelmRepository
        name: registry-lab
        namespace: flux-system
  values:
    global:
      imageRegistry: registry.lab.reisman.org/proxy.docker.io
      storageClass: nfs-client-nobackup
    architecture: standalone
    primary:
      livenessProbe:
        initialDelaySeconds: 120
    auth:
      database: paperless
      username: paperless
      existingSecret: paperless-secrets
      secretKeys:
        adminPasswordKey: postgresql-admin-password
        userPasswordKey: postgresql-user-password
      usePasswordFiles: false
    backup:
      enabled: true
      storage:
        storageClass: ${vals_infra_csi_nfsSubdir_backupStorageClass}
    metrics:
      enabled: false
      image:
        registry: registry.lab.reisman.org/proxy.docker.io
