apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  chart:
    spec:
      chart: cert-manager
      version: "v1.19.1"
      sourceRef:
        kind: HelmRepository
        name: cert-manager
        namespace: cert-manager
      interval: 6h
  interval: 30m
  values:
    installCRDs: true
    replicaCount: 2
    podDisruptionBudget:
      enabled: true
    webhook:
      replicaCount: 2
      podDisruptionBudget:
        enabled: true
    cainjector:
      replicaCount: 2
      podDisruptionBudget:
        enabled: true
    prometheus:
      enabled: true
