apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mud-server-characters
  namespace: games
spec:
  storageClassName: ${vals_infra_csi_nfsSubdir_backupStorageClass}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
