apiVersion: v1
kind: Secret
metadata:
  name: romm-secrets
  namespace: games
type: Opaque
stringData:
  auth-secret-key: ${secrets_apps_games_romm_authSecretKey}
  oidc-client-id: ${secrets_apps_auth_applications_romm_clientId}
  oidc-client-secret: ${secrets_apps_auth_applications_romm_clientSecret}
