apiVersion: apps/v1
kind: Deployment
metadata:
  name: clamav-server
  namespace: mail
  annotations:
    reloader.stakater.com/auto: "true"
  labels:
    app.kubernetes.io/name: "clamav"
    app.kubernetes.io/instance: "clamav"
    app.kubernetes.io/component: "server"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: "clamav"
      app.kubernetes.io/instance: "clamav"
      app.kubernetes.io/component: "server"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "clamav"
        app.kubernetes.io/instance: "clamav"
        app.kubernetes.io/component: "server"
    spec:
      containers:
        - name: clamav
          image: docker.io/clamav/clamav:1.4.3-53
          imagePullPolicy: IfNotPresent
          env:
            - name: CLAMAV_NO_MILTERD
              value: "false"
          ports:
            - name: clamd
              containerPort: 3310
              protocol: TCP
            - name: milter
              containerPort: 7357
              protocol: TCP
          startupProbe:
            failureThreshold: 60
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
            exec:
              command:
                - sh
                - -c
                - /scripts/healthcheck.sh
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - /scripts/healthcheck.sh
            failureThreshold: 3
            initialDelaySeconds: 60
            periodSeconds: 10
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - /scripts/healthcheck.sh
            failureThreshold: 3
            initialDelaySeconds: 60
            periodSeconds: 10
          resources:
            requests:
              memory: "2000Mi"
              cpu: "500m"
            limits:
              memory: "2500Mi"
              cpu: "1"
          volumeMounts:
            - name: scripts
              mountPath: /scripts
      volumes:
        - name: scripts
          configMap:
            name: clamav-config-scripts
            defaultMode: 0777
