apiVersion: apps/v1
kind: Deployment
metadata:
  name: dovecot-server
  namespace: mail
  annotations:
    reloader.stakater.com/auto: "true"
  labels:
    app.kubernetes.io/name: "dovecot"
    app.kubernetes.io/instance: "dovecot"
    app.kubernetes.io/component: "server"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: "dovecot"
      app.kubernetes.io/instance: "dovecot"
      app.kubernetes.io/component: "server"
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9090"
      labels:
        app.kubernetes.io/name: "dovecot"
        app.kubernetes.io/instance: "dovecot"
        app.kubernetes.io/component: "server"
    spec:
      containers:
        - name: dovecot
          image: registry.lab.reisman.org/proxy.docker.io/dovecot/dovecot:2.4.0
          imagePullPolicy: IfNotPresent
          env:
            - name: DOVECOT_TLS_CERT_FILE
              value: "/var/certificate/tls.crt"
            - name: DOVECOT_TLS_KEY_FILE
              value: "/var/certificate/tls.key"
          ports:
            - name: pop3
              containerPort: 31110
              protocol: TCP
            - name: pop3s
              containerPort: 31990
              protocol: TCP
            - name: imap
              containerPort: 31143
              protocol: TCP
            - name: imaps
              containerPort: 31993
              protocol: TCP
            - name: submission
              containerPort: 31587
              protocol: TCP
            - name: lmtp
              containerPort: 31024
              protocol: TCP
            - name: sieve
              containerPort: 34190
              protocol: TCP
            - name: health
              containerPort: 5001
              protocol: TCP
            - name: monitoring
              containerPort: 9090
              protocol: TCP
            - name: auth
              containerPort: 12345
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: health
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: health
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              memory: "50Mi"
              cpu: "100m"
            limits:
              memory: "150Mi"
              cpu: "150m"
          volumeMounts:
            - name: mailboxes
              mountPath: /srv/vmail
            - name: config-confd
              mountPath: /etc/dovecot/conf.d
            - name: certificate
              mountPath: /etc/dovecot/ssl
            - name: scripts
              mountPath: /opt/dovecot/bin
      volumes:
        - name: mailboxes
          persistentVolumeClaim:
            claimName: dovecot-mailboxes
        - name: config-confd
          secret:
            secretName: dovecot-config-confd
        - name: scripts
          configMap:
            name: dovecot-config-scripts
            defaultMode: 0777
        - name: certificate
          secret:
            secretName: mail-server-tls
