apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dovecot-mailboxes
  namespace: mail
spec:
  storageClassName: truenas-iscsi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
