apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: roundcube-postgresql
  namespace: mail
spec:
  chart:
    spec:
      chart: bitnamicharts/postgresql
      version: "15.5.38"
      sourceRef:
        kind: HelmRepository
        name: dockerio
        namespace: flux-system
      interval: 6h
  interval: 30m
  timeout: 30m
  values:
    global:
      imageRegistry: registry.lab.reisman.org/proxy.docker.io
    architecture: standalone
    primary:
      persistence:
        storageClass: nfs-client-ssd
      resourcesPreset: "${vals_apps_mail_roundcube_postgresql_resourcesPreset:=small}"
      startupProbe:
        enabled: true
        failureThreshold: 150
    auth:
      database: roundcube
      username: roundcube
      existingSecret: roundcube-secrets
      secretKeys:
        adminPasswordKey: postgresql-admin-password
        userPasswordKey: postgresql-user-password
      usePasswordFiles: false
    backup:
      enabled: true
      cronjob:
        storage:
          storageClass: ${vals_infra_csi_nfsSubdir_backupStorageClass}
    metrics:
      enabled: true
