apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: roundcube-postgresql
  namespace: mail
spec:
  interval: 5m
  timeout: 30m
  chart:
    spec:
      chart: bitnamicharts/postgresql
      version: "15.x"
      sourceRef:
        kind: HelmRepository
        name: registry-lab
        namespace: flux-system
  values:
    global:
      imageRegistry: registry.lab.reisman.org/proxy.docker.io
    architecture: standalone
    primary:
      persistence:
        storageClass: nfs-client-nobackup
      resourcesPreset: "${vals_apps_mail_roundcube_postgresql_resourcesPreset:=nano}"
      startupProbe:
        enabled: true
    auth:
      database: roundcube
      username: roundcube
      existingSecret: roundcube-secrets
      secretKeys:
        adminPasswordKey: postgresql-admin-password
        userPasswordKey: postgresql-user-password
      usePasswordFiles: false
    backup:
      enabled: true
      cronjob:
        storage:
          storageClass: ${vals_infra_csi_nfsSubdir_backupStorageClass}
    metrics:
      enabled: true
      image:
        registry: registry.lab.reisman.org/proxy.docker.io
