apiVersion: dragonflydb.io/v1alpha1
kind: Dragonfly
metadata:
  name: rspamd-dragonfly
  namespace: mail
spec:
    authentication:
      passwordFromSecret:
        name: rspamd-redis-password
        key: password
    replicas: 1
---
apiVersion: v1
kind: Secret
metadata:
  name: rspamd-redis-password
  namespace: mail
type: Opaque
stringData:
  password: ${secrets_apps_mail_rspamd_redisPassword}