apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rspamd-redis
  namespace: mail
spec:
  interval: 5m
  timeout: 30m
  chart:
    spec:
      chart: bitnamicharts/redis
      version: "18.x"
      sourceRef:
        kind: HelmRepository
        name: registry-lab
        namespace: flux-system
  values:
    global:
      imageRegistry: registry.lab.reisman.org/proxy.docker.io
    architecture: standalone
    auth:
      enabled: true
      existingSecret: rspamd-secrets
      existingSecretPasswordKey: redis-password
    master:
      persistence:
        enabled: false
        storageClass: ${vals_infra_csi_nfsSubdir_backupStorageClass}
    metrics:
      enabled: true
