apiVersion: v1
kind: Secret
metadata:
  name: rspamd-config-confd
  namespace: mail
type: Opaque
stringData:
  classifier-bayes.conf: |
    backend = "redis";
  milter_headers.conf: |
    use = ["x-spamd-bar", "x-spam-level", "authentication-results"];
    extended_spam_headers = true;
    skip_local = false;
    skip_authenticated = true;
  phishing.conf: |
    phishing {
      openphish_enabled = true;
      openphish_map = "https://www.openphish.com/feed.txt";
    }
  redis.conf: |
    servers = "rspamd-dragonfly";
    password = "${secrets_apps_mail_rspamd_redisPassword}";
  worker-proxy.inc: |
    milter = yes;
    upstream "local" {
      default = yes;
      self_scan = yes;
    }
