apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rspamd-redis
  namespace: mail
spec:
  chart:
    spec:
      chart: bitnamicharts/redis
      version: "24.0.0"
      sourceRef:
        kind: HelmRepository
        name: dockerio
        namespace: flux-system
      interval: 6h
  interval: 30m
  values:
    global:
      imageRegistry: registry.lab.reisman.org/proxy.docker.io
      security: 
        allowInsecureImages: true
    architecture: standalone
    auth:
      enabled: true
      existingSecret: rspamd-secrets
      existingSecretPasswordKey: redis-password
    master:
      persistence:
        enabled: false
        storageClass: ${vals_infra_csi_nfsSubdir_backupStorageClass}
    metrics:
      enabled: true
