apiVersion: v1
kind: Secret
metadata:
  name: volsync-restic
  namespace: mail
type: Opaque
stringData:
  RESTIC_REPOSITORY: "${vals_infra_storage_backup_repository}/${vals_info_cluster_name}/mail-dovecot-mailboxes"
  RESTIC_PASSWORD: "${secrets_infra_storage_backup_resticPassword}"
  AWS_ACCESS_KEY_ID: "${secrets_infra_storage_backup_awsAccessKeyId}"
  AWS_SECRET_ACCESS_KEY: "${secrets_infra_storage_backup_awsSecretAccessKey}"
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: dovecot-mailboxes-backup
  namespace: mail
spec:
  paused: ${vals_infra_storage_backup_paused}
  sourcePVC: dovecot-mailboxes
  trigger:
    schedule: "0 2 * * *"
  restic:
    pruneIntervalDays: 14
    repository: volsync-restic
    volumeSnapshotClassName: truenas-iscsi
    copyMethod: Snapshot
    retain:
      daily: 7
      weekly: 4
      monthly: 3
