apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb
spec:
  chart:
    spec:
      chart: metallb
      sourceRef:
        kind: HelmRepository
        name: metallb
        namespace: metallb
      version: '0.14.5'
  interval: 1h0m0s
  values:
    controller:
      image:
        repository: registry.lab.reisman.org/proxy.quay.io/metallb/controller
    speaker:
      image:
        repository: registry.lab.reisman.org/proxy.quay.io/metallb/speaker
