apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb
spec:
  chart:
    spec:
      chart: metallb
      sourceRef:
        kind: HelmRepository
        name: metallb
        namespace: metallb
      version: "0.15.2"
      interval: 6h
  interval: 30m
  values:
    controller:
      image:
        repository: registry.lab.reisman.org/proxy.quay.io/metallb/controller
    speaker:
      image:
        repository: registry.lab.reisman.org/proxy.quay.io/metallb/speaker
    prometheus:
      scrapeAnnotations: true
