apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich-postgresql
  namespace: photos
spec:
  instances: 1
  imageName: ghcr.io/tensorchord/cloudnative-vectorchord:16-0.3.0
  superuserSecret:
    name: immich-postgresql-superuser
  bootstrap:
    initdb:
      database: immich
      owner: immich
      secret:
        name: immich-postgresql-appuser
      postInitApplicationSQL:
        - CREATE EXTENSION IF NOT EXISTS "vector";
        - CREATE EXTENSION IF NOT EXISTS "vchord" CASCADE;
        - CREATE EXTENSION IF NOT EXISTS "cube" CASCADE;
        - CREATE EXTENSION IF NOT EXISTS "earthdistance" CASCADE;
  postgresql:
    shared_preload_libraries:
      - "vchord.so"
  storage:
    storageClass: nfs-client-ssd
    size: 1Gi
---
apiVersion: v1
kind: Secret
metadata:
  name: immich-postgresql-appuser
  namespace: photos
type: kubernetes.io/basic-auth
stringData:
  username: immich
  password: ${secrets_apps_photos_immich_postgresql_app_password}
---
apiVersion: v1
kind: Secret
metadata:
  name: immich-postgresql-superuser
  namespace: photos
type: kubernetes.io/basic-auth
stringData:
  username: postgres
  password: ${secrets_apps_photos_immich_postgresql_superuser_password}
