apiVersion: dragonflydb.io/v1alpha1
kind: Dragonfly
metadata:
  name: immich-dragonfly
  namespace: photos
spec:
    args:
      - "--default_lua_flags=allow-undeclared-keys"
    authentication:
      passwordFromSecret:
        name: immich-redis-password
        key: password
    replicas: 1
---
apiVersion: v1
kind: Secret
metadata:
  name: immich-redis-password
  namespace: photos
type: Opaque
stringData:
  password: ${secrets_apps_photos_immich_redisPassword}
