apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich-redis
  namespace: photos
spec:
  chart:
    spec:
      chart: bitnamicharts/redis
      version: "23.2.12"
      sourceRef:
        kind: HelmRepository
        name: dockerio
        namespace: flux-system
      interval: 6h
  interval: 30m
  values:
    global:
      imageRegistry: registry.lab.reisman.org/proxy.docker.io
      security: 
        allowInsecureImages: true
    architecture: standalone
    auth:
      existingSecret: immich-redis-password
      existingSecretPasswordKey: password
    master:
      persistence:
        enabled: false
        storageClass: ${vals_infra_csi_nfsSubdir_backupStorageClass}
    metrics:
      enabled: true
---
apiVersion: v1
kind: Secret
metadata:
  name: immich-redis-password
  namespace: photos
type: Opaque
stringData:
  password: ${secrets_apps_photos_immich_redisPassword}
