apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: immich-postgresql
  namespace: photos
spec:
  interval: 5m
  timeout: 30m
  chart:
    spec:
      chart: bitnamicharts/postgresql
      version: "15.x"
      sourceRef:
        kind: HelmRepository
        name: registry-lab
        namespace: flux-system
  values:
    global:
      imageRegistry: registry.lab.reisman.org/proxy.docker.io
    image:
      repository: pixil/bitnami-postgresql-pgvecto-rs
      debug: false
    architecture: standalone
    postgresqlSharedPreloadLibraries: "pgaudit,vectors.so"
    primary:
      persistence:
        storageClass: nfs-client-nobackup
      resourcesPreset: "${vals_apps_photos_immich_postgresql_resourcesPreset:=small}"
      startupProbe:
        enabled: true
      initdb:
        scriptsConfigMap: immich-postgresql-initdb
    auth:
      database: immich
      username: immich
      existingSecret: immich-postgresql-user
      secretKeys:
        adminPasswordKey: adminPassword
        userPasswordKey: password
      usePasswordFiles: false
    backup:
      enabled: true
      cronjob:
        storage:
          storageClass: ${vals_infra_csi_nfsSubdir_backupStorageClass}
    metrics:
      enabled: true
      image:
        registry: registry.lab.reisman.org/proxy.docker.io
---
apiVersion: v1
stringData:
  adminPassword: ${secrets_apps_photos_immich_postgresqlAdminPassword}
  password: ${secrets_apps_photos_immich_postgresqlUserPassword}
  username: immich
kind: Secret
metadata:
  name: immich-postgresql-user
  namespace: photos
type: kubernetes.io/basic-auth
