apiVersion: dragonflydb.io/v1alpha1
kind: Dragonfly
metadata:
  name: immich-dragonfly
  namespace: photos
spec:
    authentication:
      passwordFromSecret:
        name: immich-redis-password
        key: password
    replicas: 1
    image: registry.lab.reisman.org/proxy.ghcr.io/dragonflydb/dragonfly:v1.21.2
---
apiVersion: v1
kind: Secret
metadata:
  name: immich-redis-password
  namespace: photos
type: Opaque
stringData:
  password: ${secrets_apps_photos_immich_redisPassword}
