apiVersion: operator.victoriametrics.com/v1beta1
kind: VMPodScrape
metadata:
  name: immich-server
  namespace: photos
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: server
      app.kubernetes.io/instance: immich
  podMetricsEndpoints:
    - targetPort: 8081
