apiVersion: autoscaling.k8s.io/v1beta2
kind: VerticalPodAutoscaler
metadata:
  name: immich-machine-learning-vpa
  namespace: photos
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: immich-machine-learning
  updatePolicy:
    updateMode: "Off"
