apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-library
  namespace: photos
spec:
  storageClassName: truenas-nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ti
