apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich-postgresql
  namespace: photos
spec:
  instances: 1
  # https://github.com/tensorchord/cloudnative-pgvecto.rs
  imageName: registry.lab.reisman.org/proxy.ghcr.io/tensorchord/cloudnative-pgvecto.rs:16-v0.3.0
  postgresql:
    shared_preload_libraries:
      - "vectors.so"
  bootstrap:
    initdb:
      database: immich
      owner: immich
      secret:
        name: immich-postgresql-user
      dataChecksums: true
      postInitApplicationSQL:
        - ALTER SYSTEM SET search_path TO "$user", public, vectors;
        - CREATE EXTENSION IF NOT EXISTS cube
        - CREATE EXTENSION IF NOT EXISTS earthdistance
        - CREATE EXTENSION IF NOT EXISTS vectors
        - GRANT USAGE ON SCHEMA vectors TO immich
        - GRANT SELECT ON ALL TABLES IN SCHEMA vectors TO immich
  resources:
    requests:
      memory: "512Mi"
      cpu: 1
    limits:
      memory: "512Mi"
      cpu: 1
  storage:
    storageClass: this-is-unique
    size: 1Gi
---
apiVersion: v1
stringData:
  password: ${secrets_apps_photos_immich_postgresqlUserPassword}
  username: immich
kind: Secret
metadata:
  name: immich-postgresql-user
  namespace: photos
type: kubernetes.io/basic-auth
