apiVersion: v1
kind: Secret
metadata:
  name: volsync-restic
  namespace: photos
type: Opaque
stringData:
  RESTIC_REPOSITORY: "s3:${vals_infra_storage_backup_s3Endpoint}/${vals_infra_storage_backup_s3Bucket}/${vals_info_cluster_name}/photos-immich-library"
  RESTIC_PASSWORD: "${secrets_infra_storage_backup_resticPassword}"
  AWS_ACCESS_KEY_ID: "${secrets_infra_storage_backup_awsAccessKeyId}"
  AWS_SECRET_ACCESS_KEY: "${secrets_infra_storage_backup_awsSecretAccessKey}"
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: immich-library-backup
  namespace: photos
spec:
  paused: ${vals_infra_storage_backup_paused}
  sourcePVC: immich-library
  trigger:
    schedule: "0 3 * * *"
  restic:
    pruneIntervalDays: 14
    repository: volsync-restic
    copyMethod: Direct
    cacheStorageClassName: truenas-iscsi
    retain:
      daily: 7
      weekly: 4
      monthly: 3
