apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mapper-server-db
  namespace: mapper
spec:
  storageClassName: ${vals_infra_csi_nfsSubdir_backupStorageClass}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
