apiVersion: v1
kind: ConfigMap
metadata:
  name: dovecot-config
  namespace: mail
data:
  dovecot.conf: |
    # Most of the actual configuration gets included below. The filenames are
    # first sorted by their ASCII value and parsed in that order. The 00-prefixes
    # in filenames are intended to make it easier to understand the ordering.
    !include conf.d/*.conf
