apiVersion: v1
kind: ConfigMap
metadata:
  name: dovecot-config-scripts
  namespace: mail
data:
  health-check.sh: |
    #!/bin/sh

    timeout=10
    # timeout the read via trap for POSIX shell compatibility
    trap "exit 0" QUIT
    {
      sleep $timeout
      kill -3 $$ 2>/dev/null
    } &
    read -r input

    echo "OK"
    # always exit successful
    exit 0