apiVersion: v1
kind: Secret
metadata:
  name: dovecot-config
  namespace: mail
type: Opaque
stringData:
  00-nfs.conf: |
    mail_nfs_index = no
    mail_nfs_storage = no
    mail_fsync = always
    mmap_disable = yes
  10-auth.conf: |
    disable_plaintext_auth = yes
    auth_mechanisms = oauthbearer xoauth2
    passdb {
      driver = oauth2
      mechanisms = oauthbearer xoauth2
      args = /etc/dovecot/conf.d/dovecot-oauth2.conf.ext
    }
    userdb {
      driver = static
      args = uid=vmail gid=vmail home=/var/vmail/%d/%n
    }
  10-mail.conf: |
    mail_home = /var/vmail/%d/%n
    mail_location = maildir:/var/vmail/%d/%n/:LAYOUT=fs
    mail_uid = vmail
    mail_gid = vmail
    mail_privileged_group = vmail
    namespace inbox {
      inbox = yes
      # See 15-mailboxes.conf for definitions of special mailboxes.
    }
  10-ssl.conf: |
    ssl = required
    ssl_cert = </var/certificate/tls.crt
    ssl_key = </var/certificate/tls.key
    ssl_client_ca_file = /etc/ssl/certs/ca-certificates.crt
  15-mailboxes.conf: |    
    # NOTE: Assumes "namespace inbox" has been defined in 10-mail.conf.
    namespace inbox {
      inbox = yes

      mailbox Drafts {
        auto = subscribe
        special_use = \Drafts
      }
      mailbox Spam {
        auto = subscribe
        special_use = \Junk
      }
      mailbox Trash {
        auto = subscribe
        special_use = \Trash
      }

      mailbox Sent {
        auto = subscribe
        special_use = \Sent
      }
    }
  #TODO maybe remove this and related config
  50-health.conf: |
    service health-check {
      executable = script -p /opt/dovecot/bin/health-check.sh
      inet_listener health-check {
          port = 5001
      }
    }
  dovecot-oauth2.conf.ext: |
    tokeninfo_url = https://auth.${vals_info_cluster_domain}/application/o/userinfo/?access_token=
    introspection_url = https://${secrets_apps_auth_applications_dovecot_clientId}:${secrets_apps_auth_applications_dovecot_clientSecret}@auth.${vals_info_cluster_domain}/application/o/introspect/
    introspection_mode = post
    force_introspection = yes
    active_attribute = active
    active_value = true
    username_attribute = email
    tls_ca_cert_file = /etc/ssl/certs/ca-certificates.crt
