apiVersion: v1
kind: ConfigMap
metadata:
  name: dovecot-config
  namespace: mail
data:
  00-nfs.conf: |
    mail_nfs_index = no
    mail_nfs_storage = no
    mail_fsync = always
    mmap_disable = yes
  10-mail.conf: |
    mail_home = /var/vmail/%d/%n
    mail_location = maildir:/var/vmail/%d/%n/:LAYOUT=fs
    mail_uid = vmail
    mail_gid = vmail
    mail_privileged_group = vmail
    namespace inbox {
      inbox = yes
      # See 15-mailboxes.conf for definitions of special mailboxes.
    }
  10-ssl.conf: |
    ssl = required 
    ssl_cert = <env:DOVECOT_TLS_CERT_FILE
    ssl_key = <env:DOVECOT_TLS_KEY_FILE
  15-mailboxes.conf: |    
    # NOTE: Assumes "namespace inbox" has been defined in 10-mail.conf.
    namespace inbox {
      inbox = yes

      mailbox Drafts {
        auto = subscribe
        special_use = \Drafts
      }
      mailbox Spam {
        auto = subscribe
        special_use = \Junk
      }
      mailbox Trash {
        auto = subscribe
        special_use = \Trash
      }

      mailbox Sent {
        auto = subscribe
        special_use = \Sent
      }
    }
  50-health.conf: |
    service health-check {
      executable = script -p health-check.sh
      inet_listener health-check {
          port = 5001
      }
    }
