apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mail-server-tls
  namespace: mail
spec:
  secretName: mail-server-tls
  dnsNames:
    - mail.${vals_info_cluster_domain}
    - webmail.${vals_info_cluster_domain}
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: ${vals_infra_certManager_issuer}
