apiVersion: v1
kind: Secret
metadata:
  name: postfix-env
  namespace: mail
stringData:
  ALLOWED_SENDER_DOMAINS: "${vals_info_cluster_domain} ${vals_apps_mail_postfix_virtualDomains}"
  POSTFIX_myhostname: "mail.${vals_info_cluster_domain}"
  POSTFIX_mydestination: "localhost"

  # Postfix Outbound
  POSTFIX_smtp_tls_security_level: "dane"
  POSTFIX_smtp_dns_support_level: "dnssec"
  POSTFIX_smtp_tls_protocols: "!SSLv2, !SSLv3"
  POSTFIX_smtp_tls_ciphers: "high"

  # Postfix Inbound
  POSTFIX_smtpd_tls_security_level: "may"
  POSTFIX_smtpd_tls_auth_only: "yes"
  POSTFIX_smtpd_tls_protocols: "!SSLv2, !SSLv3"
  POSTFIX_smtpd_tls_cipher: "high"
  POSTFIX_smtpd_tls_cert_file: "/etc/postfix/tls/tls.crt"
  POSTFIX_smtpd_tls_key_file: "/etc/postfix/tls/tls.key"
  RELAYHOST: "${vals_apps_mail_postfix_relayHost}"
  RELAYHOST_USERNAME: "${secrets_apps_mail_postfix_relayUser}"
  RELAYHOST_PASSWORD: "${secrets_apps_mail_postfix_relayPassword}"
  POSTFIX_smtpd_helo_required: "yes"
  POSTFIX_smtpd_helo_restrictions: "permit_mynetworks reject_non_fqdn_helo_hostname reject_invalid_helo_hostname reject_unknown_helo_hostname"
  POSTFIX_smtpd_relay_restrictions: "reject_non_fqdn_recipient reject_unknown_recipient_domain permit_sasl_authenticated reject_unauth_destination"
  POSTFIX_smtpd_recipient_restrictions: "reject_unverified_recipient"
  POSTFIX_smtpd_data_restrictions: "reject_unauth_pipelining reject_multi_recipient_bounce"
  POSTFIX_unverified_recipient_reject_reason: "Address lookup failed"

  # Postfix SASL Auth
  POSTFIX_smtpd_sasl_auth_enable: "yes"
  POSTFIX_smtpd_sasl_type: "dovecot"
  POSTFIX_smtpd_sasl_path: "inet:dovecot-server-internal.mail.svc.cluster.local:12345"
  POSTFIX_smtpd_sasl_security_options: "noanonymous, noplaintext"
  POSTFIX_smtpd_sasl_tls_security_options: "noanonymous"

  # Postfix Mailbox
  POSTFIX_mailbox_size_limit: "0"
  POSTFIX_virtual_mailbox_domains: "${vals_info_cluster_domain} ${vals_apps_mail_postfix_virtualDomains}"
  POSTFIX_virtual_transport: "lmtp:dovecot-server-internal.mail.svc.cluster.local:24"

  # Spam filter
  #TODO finish this
  POSTFIX_smtpd_milters: "inet:rspamd-server.mail.svc.cluster.local:11332,inet:clamav-server.mail.svc.cluster.local:3310"
  POSTFIX_non_smtpd_milters: "inet:rspamd-server.mail.svc.cluster.local:11332,inet:clamav-server.mail.svc.cluster.local:3310"
