apiVersion: apps/v1
kind: Deployment
metadata:
  name: postfix-server
  namespace: mail
  labels:
    app.kubernetes.io/name: "postfix"
    app.kubernetes.io/instance: "postfix"
    app.kubernetes.io/component: "server"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: "postfix"
      app.kubernetes.io/instance: "postfix"
      app.kubernetes.io/component: "server"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "postfix"
        app.kubernetes.io/instance: "postfix"
        app.kubernetes.io/component: "server"
    spec:
      containers:
        - name:  postfix
          image: registry.lab.reisman.org/proxy.docker.io/dboky/postfix:4.1.0
          imagePullPolicy: IfNotPresent
          env: []
          ports:
            - name: smtp
              containerPort: 25
              protocol: TCP
            - name: submission
              containerPort: 587
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: health
          #   initialDelaySeconds: 5
          #   periodSeconds: 10
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: health
          #   initialDelaySeconds: 5
          #   periodSeconds: 10
          volumeMounts: []
      volumes: []
