apiVersion: apps/v1
kind: Deployment
metadata:
  name: roundcube-server
  namespace: mail
  labels:
    app.kubernetes.io/name: "roundcube"
    app.kubernetes.io/instance: "roundcube"
    app.kubernetes.io/component: "server"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: "roundcube"
      app.kubernetes.io/instance: "roundcube"
      app.kubernetes.io/component: "server"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "roundcube"
        app.kubernetes.io/instance: "roundcube"
        app.kubernetes.io/component: "server"
    spec:
      containers:
        - name:  roundcube
          image: registry.lab.reisman.org/proxy.docker.io/roundcube/roundcubemail:1.6.6-fpm
          imagePullPolicy: IfNotPresent
          env:
            - name: ROUNDCUBEMAIL_DB_TYPE
              value: "pgsql"
            - name: ROUNDCUBEMAIL_DB_HOST
              value: "roundcube-postgresql"
            - name: ROUNDCUBEMAIL_DB_NAME
              value: "roundcube"
            - name: ROUNDCUBEMAIL_DB_USER
              value: "roundcube"
            - name: ROUNDCUBEMAIL_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: roundcube-secrets
                  key: postgresql-user-password
            - name: ROUNDCUBEMAIL_DES_KEY
              value: "TODO CHANGE THIS KEY TO A SECRET"
            - name: ROUNDCUBEMAIL_DEFAULT_HOST
              value: "tls://mail.${vals_info_cluster_domain}"
            - name: ROUNDCUBEMAIL_SMTP_SERVER
              value: "tls://mail.${vals_info_cluster_domain}"
            - name: ROUNDCUBEMAIL_SKIN
              value: "elastic"
            - name: ROUNDCUBEMAIL_PLUGINS
              value: "archive,zipdownload,newmail_notifier"
          ports:
            - name: fastcgi
              containerPort: 9000
              protocol: TCP
          volumeMounts:
            - name: www-data
              mountPath: /var/www/html
        - name: nginx
          image: registry.lab.reisman.org/proxy.docker.io/nginx:stable
          imagePullPolicy: Always
          env:
            - name: NGINX_HOST
              value: localhost
            - name: NGINX_PHP_CGI
              value: localhost:9000
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: www-data
              mountPath: /var/www/html
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
      volumes:
      - name: www-data
        emptydir: {}
      - name: nginx-config
        configMap:
          name: roundcube-nginx-config
