apiVersion: v1
kind: ConfigMap
metadata:
  name: roundcube-nginx-config
  namespace: mail
data:
  default.conf: |
    server {
      listen 8080 default_server;
      server_name _;
      root /var/www/html;

      location / {
        try_files $uri /index.php$is_args$args;
      }

      location ~ ^/(CHANGELOG.md|INSTALL|LICENSE|README.md|SECURITY.md|UPGRADING)$ {
        deny all;
      }

      location ~ ^/(bin|SQL)/ {
        deny all;
      }

      location ~ \.php$ {
        try_files $uri =404;
        fastcgi_pass localhost:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param SERVER_PORT 443;
        #internal;
      }

      client_max_body_size 6m;

      error_log  /var/log/nginx/error.log;
      access_log /var/log/nginx/access.log;
    }
