apiVersion: v1
kind: Secret
metadata:
  name: roundcube-server-config
  namespace: mail
type: Opaque
stringData:
  connections.php: |
    <?php
      $config['imap_conn_options'] = array(
              'ssl' => array(
                'peer_name' => 'mail.${vals_info_cluster_domain}',
                'verify_peer' => true,
                'verify_peer_name' => true,
                'allow_self_signed' => true,
              ),
              'tls' => array(
                'peer_name' => 'mail.${vals_info_cluster_domain}',
                'verify_peer' => true,
                'verify_peer_name' => true,
                'allow_self_signed' => true,
              ),
      );
      $config['smtp_conn_options'] = array(
              'ssl' => array(
                'peer_name' => 'mail.${vals_info_cluster_domain}',
                'verify_peer' => true,
                'verify_peer_name' => true,
                'allow_self_signed' => true,
              ),
              'tls' => array(
                'peer_name' => 'mail.${vals_info_cluster_domain}',
                'verify_peer' => true,
                'verify_peer_name' => true,
                'allow_self_signed' => true,
              ),
      );
    ?>
  oauth.php: |
    <?php
      $config['oauth_provider'] = 'generic';
      $config['oauth_provider_name'] = 'Authentik';
      $config['oauth_client_id'] = '${secrets_apps_auth_applications_dovecot_clientId}';
      $config['oauth_client_secret'] = '${secrets_apps_auth_applications_dovecot_clientSecret}';
      $config['oauth_auth_uri'] = 'https://auth.${vals_info_cluster_domain}/application/o/authorize/';
      $config['oauth_token_uri'] = 'https://auth.${vals_info_cluster_domain}/application/o/token/';
      $config['oauth_identity_uri'] = 'https://auth.${vals_info_cluster_domain}/application/o/userinfo/';
      $config['oauth_scope'] = "email openid dovecot-profile";
      $config['oauth_auth_parameters'] = [];
      $config['oauth_identity_fields'] = ['email'];
      $config['oauth_login_redirect'] = true;
    ?>
