apiVersion: v1
kind: Service
metadata:
  name: roundcube-server
  namespace: mail
  labels:
    app.kubernetes.io/name: "roundcube"
    app.kubernetes.io/instance: "roundcube"
    app.kubernetes.io/component: "server"
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
  selector:
    app.kubernetes.io/name: "roundcube"
    app.kubernetes.io/instance: "roundcube"
    app.kubernetes.io/component: "server"
