apiVersion: v1
kind: ConfigMap
metadata:
  name: roundcube-nginx-config
  namespace: mail
data:
  default.conf: |
    server {
        listen 8080 default_server;
        server_name _;
        root /var/www/html;

        location / {
            try_files $uri /index.php$is_args$args;
        }

        location ~ \.php(/|$) {
            try_files $uri =404;
            fastcgi_pass localhost:9000;
            fastcgi_read_timeout 300;
            proxy_read_timeout 300;
            fastcgi_split_path_info ^(.+\.php)(/.*)$;
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
            fastcgi_param DOCUMENT_ROOT $realpath_root;
            #fastcgi_param REDIRECT_SCRIPT_URL $http_x_forwarded_prefix$request_uri;
            #fastcgi_param SERVER_PORT 443;
            internal;
        }

        client_max_body_size 6m;

        error_log  /var/log/nginx/error.log;
        access_log /var/log/nginx/access.log;
    }
