apiVersion: v1
kind: Secret
metadata:
  name: roundcube-server-config
  namespace: mail
type: Opaque
stringData:
  connections.php: |
    <?php
      $_SERVER['HTTPS'] = 'on';
      $config['imap_conn_options'] = array(
              'ssl' => array(
                'peer_name' => 'mail.${vals_info_cluster_domain}',
                'verify_peer' => true,
                'verify_peer_name' => true,
                'allow_self_signed' => true,
              ),
              'tls' => array(
                'peer_name' => 'mail.${vals_info_cluster_domain}',
                'verify_peer' => true,
                'verify_peer_name' => true,
                'allow_self_signed' => true,
              ),
      );
      $config['smtp_conn_options'] = array(
              'ssl' => array(
                'peer_name' => 'mail.${vals_info_cluster_domain}',
                'verify_peer' => true,
                'verify_peer_name' => true,
                'allow_self_signed' => true,
              ),
              'tls' => array(
                'peer_name' => 'mail.${vals_info_cluster_domain}',
                'verify_peer' => true,
                'verify_peer_name' => true,
                'allow_self_signed' => true,
              ),
      );
    ?>
  logging.php: |
    <?php
      // Log sent messages to <log_dir>/sendmail.log or to syslog
      $config['smtp_log'] = false;

      // Log successful/failed logins to <log_dir>/userlogins.log or to syslog
      $config['log_logins'] = true;

      // Log session debug information/authentication errors to <log_dir>/session.log or to syslog
      $config['session_debug'] = true;

      // Log SQL queries to <log_dir>/sql.log or to syslog
      $config['sql_debug'] = false;

      // Log IMAP conversation to <log_dir>/imap.log or to syslog
      $config['imap_debug'] = true;

      // Log LDAP conversation to <log_dir>/ldap.log or to syslog
      $config['ldap_debug'] = false;

      // Log SMTP conversation to <log_dir>/smtp.log or to syslog
      $config['smtp_debug'] = false;

      // Log Memcache conversation to <log_dir>/memcache.log or to syslog
      $config['memcache_debug'] = false;

      // Log APC conversation to <log_dir>/apc.log or to syslog
      $config['apc_debug'] = false;

      // Log Redis conversation to <log_dir>/redis.log or to syslog
      $config['redis_debug'] = false;
    ?>
  oauth.php: |
    <?php
      $config['oauth_provider'] = 'generic';
      $config['oauth_provider_name'] = 'Authentik';
      $config['oauth_client_id'] = '${secrets_apps_auth_applications_dovecot_clientId}';
      $config['oauth_client_secret'] = '${secrets_apps_auth_applications_dovecot_clientSecret}';
      $config['oauth_auth_uri'] = 'https://auth.${vals_info_cluster_domain}/application/o/authorize/';
      $config['oauth_token_uri'] = 'https://auth.${vals_info_cluster_domain}/application/o/token/';
      $config['oauth_identity_uri'] = 'https://auth.${vals_info_cluster_domain}/application/o/userinfo/';
      $config['oauth_scope'] = "email openid dovecot-profile";
      $config['oauth_auth_parameters'] = [];
      $config['oauth_identity_fields'] = ['email'];
      $config['oauth_login_redirect'] = true;
    ?>
