apiVersion: v1
kind: Secret
metadata:
  name: roundcube-secrets
  namespace: mail
type: Opaque
stringData:
  postgresql-admin-password: ${secrets_apps_auth_roundcube_postgresqlAdminPassword}
  postgresql-user-password: ${secrets_apps_auth_roundcube_postgresqlUserPassword}
#redis-password: ${secrets_apps_auth_authentik_redisPassword}
