apiVersion: v1
kind: Secret
metadata:
  name: rspamd-config-confd
  namespace: mail
type: Opaque
stringData:
  classifier-bayes.conf: |
    backend = "redis";
  milter_headers.conf: |
    use = ["x-spamd-bar", "x-spam-level", "authentication-results"];
  phishing.conf: |
    phishing {
      symbol = "R_PHISHING"; # Default symbol

      # Enable openphish support (default disabled)
      openphish_enabled = true;
      # URL of feed, default is public url:
      openphish_map = "https://www.openphish.com/feed.txt";
    }
  redis.conf: |
    servers = "rspamd-redis-master";
    password = "${secrets_apps_mail_rspamd_redisPassword}";
  worker-proxy.inc: |
    milter = yes;
    upstream "local" {
      default = yes;
      self_scan = yes;
    }
