apiVersion: apps/v1
kind: Deployment
metadata:
  name: rspamd-server
  namespace: mail
  labels:
    app.kubernetes.io/name: "rspamd"
    app.kubernetes.io/instance: "rspamd"
    app.kubernetes.io/component: "server"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: "rspamd"
      app.kubernetes.io/instance: "rspamd"
      app.kubernetes.io/component: "server"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "rspamd"
        app.kubernetes.io/instance: "rspamd"
        app.kubernetes.io/component: "server"
    spec:
      containers:
        - name:  rspamd
          image: registry.lab.reisman.org/proxy.docker.io/rspamd/rspamd:3.8.4
          imagePullPolicy: IfNotPresent
          env: []
          ports:
            - name: proxy
              containerPort: 11332
              protocol: TCP
            - name: normal
              containerPort: 11333
              protocol: TCP
            - name: controller
              containerPort: 11334
              protocol: TCP
          livenessProbe:
            exec:
              command:
                - curl
                - -f
                - -L
                - http://localhost:11334/
            initialDelaySeconds: 10
            timeoutSeconds: 5
            periodSeconds: 60
          readinessProbe:
            exec:
              command:
                - curl
                - -f
                - -L
                - http://localhost:11334/
            initialDelaySeconds: 10
            timeoutSeconds: 5
            periodSeconds: 60
          volumeMounts: []
      volumes: []
