apiVersion: v1
kind: Secret
metadata:
  name: authoritative-bind-letsencrypt-keys
  namespace: dns
type: Opaque
stringData:
  letsencrypt_key.conf: |
    key "letsencrypt" {
      algorithm hmac-sha256;
      secret "${secrets_apps_dns_authoritative_letsencryptKey}";
    };
