apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: csi-driver-nfs
  namespace: csi
spec:
  chart:
    spec:
      chart: csi-driver-nfs
      version: "4.13.1"
      sourceRef:
        kind: HelmRepository
        name: csi-driver-nfs
        namespace: csi
      interval: 6h
  interval: 30m
  values:
    controller:
      defaultOnDeletePolicy: retain

    storageClass:
      create: false

    externalSnapshotter:
      enabled: true
      customResourceDefinitions:
        enabled: true

    volumeSnapshotClass:
      create: false
