apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: csi-driver-nfs
  namespace: csi
spec:
  chart:
    spec:
      chart: csi-driver-nfs
      version: "4.x"
      sourceRef:
        kind: HelmRepository
        name: csi-driver-nfs
        namespace: csi
  interval: 1h0m0s
  values:
    image:
      baseRepo: registry.lab.reisman.org/proxy.registry.k8s.io
      nfs:
          repository: registry.lab.reisman.org/proxy.gcr.io/k8s-staging-sig-storage/nfsplugin
      csiProvisioner:
          repository: registry.lab.reisman.org/proxy.registry.k8s.io/sig-storage/csi-provisioner
      csiResizer:
          repository: registry.lab.reisman.org/proxy.registry.k8s.io/sig-storage/csi-resizer
      csiSnapshotter:
          repository: registry.lab.reisman.org/proxy.registry.k8s.io/sig-storage/csi-snapshotter
      livenessProbe:
          repository: registry.lab.reisman.org/proxy.registry.k8s.io/sig-storage/livenessprobe
      nodeDriverRegistrar:
          repository: registry.lab.reisman.org/proxy.registry.k8s.io/sig-storage/csi-node-driver-registrar
      externalSnapshotter:
          repository: registry.lab.reisman.org/proxy.registry.k8s.io/sig-storage/snapshot-controller
    defaultOnDeletePolicy: ${vals_infra_csi_nfsSubdir_reclaimPolicy}
    externalSnapshotter:
      enabled: true