apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nfs-subdir-backup
  namespace: csi
spec:
  chart:
    spec:
      chart: nfs-subdir-external-provisioner
      version: "4.0.18"
      sourceRef:
        kind: HelmRepository
        name: nfs-subdir-external-provisioner
        namespace: csi
  interval: 1h0m0s
  values:
    image:
      repository: registry.lab.reisman.org/proxy.registry.k8s.io/sig-storage/nfs-subdir-external-provisioner
    nfs:
      server: 192.168.1.10
      path: /mnt/main/kubernetes
      reclaimPolicy: Retain
    storageClass:
      name: nfs-client-backup
      provisionerName: k8s-sigs.io/nfs-subdir-external-provisioner-backup
      pathPattern: "${vals_info_cluster_name}/$${.PVC.namespace}-$${.PVC.name}"
      reclaimPolicy: ${vals_infra_csi_nfsSubdir_reclaimPolicy}
