apiVersion: autoscaling.k8s.io/v1beta2
kind: VerticalPodAutoscaler
metadata:
  name: metallb-speaker-vpa
  namespace: metallb
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: DaemonSet
    name: metallb-speaker
  updatePolicy:
    updateMode: "Off"
