apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentik-worker
  namespace: auth
  labels:
    app.kubernetes.io/name: worker
    app.kubernetes.io/instance: authentik
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: worker
      app.kubernetes.io/instance: authentik
  template:
    metadata:
      labels:
        app.kubernetes.io/name: worker
        app.kubernetes.io/instance: authentik
    spec:
      containers:
        - name: authentik
          image: registry.lab.reisman.org/proxy.ghcr.io/goauthentik/server:2023.10.4
          imagePullPolicy: IfNotPresent
          args: ["worker"]
          env:
            - name: AUTHENTIK_AVATARS
              value: "gravatar"
            - name: AUTHENTIK_EMAIL__FROM
              value: "authentik@reisman.org"
            - name: AUTHENTIK_EMAIL__HOST
              value: "mail.reisman.org"
            - name: AUTHENTIK_EMAIL__PASSWORD
              value: "${secrets_apps_auth_authentik_emailPassword}"
            - name: AUTHENTIK_EMAIL__PORT
              value: "587"
            - name: AUTHENTIK_EMAIL__TIMEOUT
              value: "30"
            - name: AUTHENTIK_EMAIL__USE_SSL
              value: "false"
            - name: AUTHENTIK_EMAIL__USE_TLS
              value: "true"
            - name: AUTHENTIK_EMAIL__USERNAME
              value: "authentik"
            - name: AUTHENTIK_ERROR_REPORTING__ENABLED
              value: "false"
            - name: AUTHENTIK_ERROR_REPORTING__ENVIRONMENT
              value: "k8s"
            - name: AUTHENTIK_ERROR_REPORTING__SEND_PII
              value: "false"
            - name: AUTHENTIK_GEOIP
              value: "/geoip/GeoLite2-City.mmdb"
            - name: AUTHENTIK_LOG_LEVEL
              value: "info"
            - name: AUTHENTIK_OUTPOSTS__CONTAINER_IMAGE_BASE
              value: "registry.lab.reisman.org/proxy.ghcr.io/goauthentik/%(type)s:%(version)s"
            - name: AUTHENTIK_POSTGRESQL__HOST
              value: "authentik-postgresql"
            - name: AUTHENTIK_POSTGRESQL__NAME
              value: "authentik"
            - name: AUTHENTIK_POSTGRESQL__PASSWORD
              value: "${secrets_apps_auth_authentik_postgresqlUserPassword}"
            - name: AUTHENTIK_POSTGRESQL__PORT
              value: "5432"
            - name: AUTHENTIK_POSTGRESQL__USER
              value: "authentik"
            - name: AUTHENTIK_REDIS__HOST
              value: "authentik-redis-master"
            - name: AUTHENTIK_REDIS__PASSWORD
              value: "${secrets_apps_auth_authentik_redisPassword}"
            - name: AUTHENTIK_SECRET_KEY
              value: "${secrets_apps_auth_authentik_secretKey}"
