apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich-server
  namespace: photos
  annotations:
    reloader.stakater.com/auto: "true"
  labels:
    app.kubernetes.io/instance: immich
    app.kubernetes.io/name: server
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: server
      app.kubernetes.io/instance: immich
  template:
    metadata:
      labels:
        app.kubernetes.io/name: server
        app.kubernetes.io/instance: immich
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8081"
    spec:
      containers:
        - name: immich-server
          image: registry.lab.reisman.org/proxy.ghcr.io/immich-app/immich-server:v1.121.0
          imagePullPolicy: IfNotPresent
          env:
            - name: TZ
              value: "America/Chicago"
            - name: DB_DATABASE_NAME
              value: "immich"
            - name: DB_HOSTNAME
              value: "immich-postgresql"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: immich-secrets
                  key: postgresql-user-password
                  optional: false
            - name: DB_USERNAME
              value: "immich"
            - name: IMMICH_CONFIG_FILE
              value: "/config/immich.json"
            - name: IMMICH_TELEMETRY_INCLUDE
              value: "all"
            - name: IMMICH_IGNORE_MOUNT_CHECK_ERRORS
              value: "true"
            - name: REDIS_HOSTNAME
              value: "immich-redis-master"
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: immich-secrets
                  key: redis-password
                  optional: false
          ports:
            - name: http
              containerPort: 2283
              protocol: TCP
            - name: monitoring
              containerPort: 8081
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /config
            - name: library
              mountPath: /usr/src/app/upload/library
            - name: upload
              mountPath: /usr/src/app/upload/upload
            - name: encoded-video
              mountPath: /usr/src/app/upload/encoded-video
            - name: profile
              mountPath: /usr/src/app/upload/profile
            - name: thumbs
              mountPath: /usr/src/app/upload/thumbs
          startupProbe:
            httpGet:
              path: /api/server/ping
              port: http
            failureThreshold: 60
            periodSeconds: 5
          livenessProbe:
            failureThreshold: 30
            httpGet:
              path: /api/server/ping
              port: http
            periodSeconds: 60
            timeoutSeconds: 1
      volumes:
        - name: config
          secret:
            secretName: immich-server-config
        - name: library
          persistentVolumeClaim:
            claimName: immich-library
        - name: upload
          persistentVolumeClaim:
            claimName: immich-upload
        - name: encoded-video
          persistentVolumeClaim:
            claimName: immich-encoded-video
        - name: profile
          persistentVolumeClaim:
            claimName: immich-profile
        - name: thumbs
          persistentVolumeClaim:
            claimName: immich-thumbs
