apiVersion: v1
kind: Secret
metadata:
  name: authentik-blueprint-ldap
  namespace: auth
type: Opaque
stringData:
  ldap.yaml: |
    # yaml-language-server: $schema=https://goauthentik.io/blueprints/schema.json
    version: 1
    metadata: { name: Custom - LDAP }
    entries:
      - model: authentik_core.group
        id: ldap_group
        state: present
        identifiers: { name: ldapsearch }
        attrs: { name: ldapsearch }

      - model: authentik_core.user
        id: ldap_user
        identifiers: { username: service-ldap }
        state: present
        attrs:
          name: service-ldap
          type: service_account
          is_active: true
          groups: [ !KeyOf ldap_group ]
          path: goauthentik.io/service-accounts
          password: ${secrets_apps_auth_authentik_outpost_ldap_password}
          attributes:
            goauthentik.io/user/token-expires: false

      - model: authentik_providers_ldap.ldapprovider
        id: ldap_provider
        identifiers: { name: ldap }
        state: present
        attrs:
          authorization_flow: !Find [authentik_flows.flow, [slug, default-authentication-flow]]
          invalidation_flow: !Find [authentik_flows.flow, [slug, default-provider-invalidation-flow]]
          certificate: !Find [authentik_crypto.certificatekeypair, [name, auth.${vals_info_cluster_domain}]]
          tls_server_name: auth.${vals_info_cluster_domain}
          base_dn: DC=ldap,DC=goauthentik,DC=io
          search_mode: "direct"
          bind_mode: "direct"
          mfa_support: false
        permissions:
          - permission: search_full_directory
            user: !KeyOf ldap_user

      - model: authentik_core.application
        id: ldap_app
        identifiers: { slug: ldap }
        state: present
        attrs:
          name: ldap
          slug: ldap
          provider: !KeyOf ldap_provider

      - model: authentik_policies.policybinding
        identifiers:
          target: !KeyOf ldap_app
          group:  !KeyOf ldap_group
        attrs:
          order: 10

      - model: authentik_policies.policybinding
        identifiers:
          target: !KeyOf ldap_app
          group:  !Find [authentik_core.group, [name, mail-users]]
        attrs:
          order: 20

      - model: authentik_outposts.outpost
        identifiers: { name: LDAP Outpost }
        state: present
        attrs:
          type: ldap
          providers: [ !KeyOf ldap_provider ]
          config: {}
