apiVersion: v1
kind: Secret
metadata:
  name: authentik-blueprint-paperless
  namespace: auth
type: Opaque
stringData:
  paperless.yaml: |
    # yaml-language-server: $schema=https://goauthentik.io/blueprints/schema.json
    version: 1
    metadata:
      name: Custom - Paperless
    entries:
      - model: authentik_providers_oauth2.oauth2provider
        id: paperless_provider
        identifiers: { name: paperless }
        state: present
        attrs:
          authentication_flow: !Find [authentik_flows.flow, [slug, default-authentication-flow]]
          authorization_flow: !Find [authentik_flows.flow, [slug, default-provider-authorization-explicit-consent]]
          invalidation_flow: !Find [authentik_flows.flow, [slug, default-provider-invalidation-flow]]
          client_type: confidential
          client_id: ${secrets_apps_auth_applications_paperless_clientId}
          client_secret: ${secrets_apps_auth_applications_paperless_clientSecret}
          redirect_uris:
            - { matching_mode: strict, url: "https://paperless.${vals_info_cluster_domain}/accounts/oidc/authentik/login/callback/" }
          access_code_validity: minutes=1
          access_token_validity: minutes=30
          refresh_token_validity: days=30
          signing_key: !Find [authentik_crypto.certificatekeypair, [name, auth.${vals_info_cluster_domain}]]
          property_mappings:
            - !Find [authentik_providers_oauth2.scopemapping, [scope_name, openid]]
            - !Find [authentik_providers_oauth2.scopemapping, [scope_name, email]]
            - !Find [authentik_providers_oauth2.scopemapping, [scope_name, profile]]
            - !Find [authentik_providers_oauth2.scopemapping, [scope_name, offline_access]]

      - model: authentik_core.application
        id: paperless_app
        identifiers: { slug: paperless }
        state: present
        attrs:
          name: Paperless
          slug: paperless
          provider: !KeyOf paperless_provider
          meta_launch_url: https://paperless.${vals_info_cluster_domain}/
          icon: icons/paperless-ngx.svg
          policy_engine_mode: any

      - model: authentik_core.group
        id: paperless_group
        identifiers: { name: paperless }
        state: present
        attrs: { name: paperless }

      - model: authentik_policies.policybinding
        identifiers:
          target: !KeyOf paperless_app
          group:  !KeyOf paperless_group
        attrs: { order: 10 }

      - model: authentik_policies.policybinding
        identifiers:
          target: !KeyOf paperless_app
          group: !Find [authentik_core.group, [name, authentik Admins]]
        attrs: { order: 20 }

      - model: authentik_core.user
        identifiers: { username: service-paperless }
        state: present
        attrs:
          name: service-paperless
          email: paperless@${vals_info_cluster_domain}
          type: service_account
          is_active: true
          groups: [ !Find [authentik_core.group, [name, mail-users]] ]
          path: goauthentik.io/service-accounts
          password: ${secrets_apps_paperless_paperless_account_password}
          attributes:
            goauthentik.io/user/service-account: true
