apiVersion: v1
kind: Secret
metadata:
  name: authentik-blueprint-roundcube
  namespace: auth
type: Opaque
stringData:
  roundcube.yaml: |
    # yaml-language-server: $schema=https://goauthentik.io/blueprints/schema.json
    version: 1
    metadata:
      name: Custom - Roundcube
    entries:
      - model: authentik_blueprints.metaapplyblueprint
        attrs:
          identifiers: { name: Custom - Common Functionality }
          required: true
      # Ensure the Dovecot blueprint (group + custom scope mapping) is applied first
      - model: authentik_blueprints.metaapplyblueprint
        attrs:
          identifiers: { name: Custom - Dovecot }
          required: true

      - model: authentik_providers_oauth2.oauth2provider
        id: roundcube
        identifiers: { name: roundcube }
        state: present
        attrs:
          authentication_flow: !Find [authentik_flows.flow, [slug, default-authentication-flow]]
          authorization_flow: !Find [authentik_flows.flow, [slug, default-provider-authorization-explicit-consent]]
          invalidation_flow: !Find [authentik_flows.flow, [slug, default-provider-invalidation-flow]]
          client_type: confidential
          client_id: ${secrets_apps_auth_applications_roundcube_clientId}
          client_secret: ${secrets_apps_auth_applications_roundcube_clientSecret}
          redirect_uris:
            - { matching_mode: strict, url: https://mail.${vals_info_cluster_domain}/index.php?_task=settings&_action=plugin.oauth_redirect }
            - { matching_mode: strict, url: https://webmail.${vals_info_cluster_domain}/index.php?_task=settings&_action=plugin.oauth_redirect }
          access_code_validity: minutes=1
          access_token_validity: minutes=30
          signing_key: !Find [authentik_crypto.CertificateKeyPair, [name, auth.${vals_info_cluster_domain}]]
          property_mappings:
            - !Find [authentik_providers_oauth2.ScopeMapping, [scope_name, openid]]
            - !Find [authentik_providers_oauth2.ScopeMapping, [scope_name, email]]
            - !Find [authentik_providers_oauth2.ScopeMapping, [scope_name, offline_access]]
            - !Find [authentik_providers_oauth2.ScopeMapping, [scope_name, dovecot_profile]]

      - model: authentik_core.application
        id: roundcube
        identifiers: { slug: roundcube }
        state: present
        attrs:
          name: Roundcube
          slug: roundcube
          provider: !KeyOf roundcube
          meta_launch_url: https://webmail.${vals_info_cluster_domain}/
          icon: /icons/roundcube.svg
          policy_engine_mode: any

      - model: authentik_policies.PolicyBinding
        identifiers:
          target: !KeyOf roundcube
          group:  !Find [authentik_core.group, [name, mail-users]]
        attrs: { order: 10 }

      - model: authentik_policies.PolicyBinding
        identifiers:
          target: !KeyOf roundcube
          group: !Find [authentik_core.group, [name, authentik Admins]]
        attrs:
          order: 20
