apiVersion: v1
kind: Secret
metadata:
  name: immich-server-config
  namespace: photos
type: Opaque
stringData:
  immich.json: |
    {
      "ffmpeg": {
        "crf": 31,
        "threads": 0,
        "preset": "veryslow",
        "targetVideoCodec": "vp9",
        "acceptedVideoCodecs": ["h264", "vp9"],
        "targetAudioCodec": "aac",
        "acceptedAudioCodecs": ["aac", "mp3", "libopus"],
        "targetResolution": "original",
        "maxBitrate": "0",
        "bframes": -1,
        "refs": 0,
        "gopSize": 0,
        "npl": 0,
        "temporalAQ": false,
        "cqMode": "auto",
        "twoPass": true,
        "preferredHwDevice": "auto",
        "transcode": "required",
        "tonemap": "hable",
        "accel": "disabled"
      },
      "job": {
        "backgroundTask": {
          "concurrency": ${vals_apps_photos_immich_jobs_backgroundTask_concurrency:=5}
        },
        "smartSearch": {
          "concurrency": ${vals_apps_photos_immich_jobs_smartSearch_concurrency:=2}
        },
        "metadataExtraction": {
          "concurrency": ${vals_apps_photos_immich_jobs_metadataExtraction_concurrency:=5}
        },
        "faceDetection": {
          "concurrency": ${vals_apps_photos_immich_jobs_faceDetection_concurrency:=2}
        },
        "search": {
          "concurrency": ${vals_apps_photos_immich_jobs_search_concurrency:=5}
        },
        "sidecar": {
          "concurrency": ${vals_apps_photos_immich_jobs_sidecar_concurrency:=5}
        },
        "library": {
          "concurrency": ${vals_apps_photos_immich_jobs_library_concurrency:=5}
        },
        "migration": {
          "concurrency": ${vals_apps_photos_immich_jobs_migration_concurrency:=5}
        },
        "thumbnailGeneration": {
          "concurrency": ${vals_apps_photos_immich_jobs_thumbnailGeneration_concurrency:=5}
        },
        "videoConversion": {
          "concurrency": ${vals_apps_photos_immich_jobs_videoConversion_concurrency:=1}
        }
      },
      "logging": {
        "enabled": true,
        "level": "${vals_apps_photos_immich_logLevel:=log}"
      },
      "machineLearning": {
        "enabled": true,
        "url": "http://immich-machine-learning:3003",
        "clip": {
          "enabled": true,
          "modelName": "ViT-B-32__openai"
        },
        "facialRecognition": {
          "enabled": true,
          "modelName": "buffalo_l",
          "minScore": 0.7,
          "maxDistance": 0.6,
          "minFaces": 3
        }
      },
      "map": {
        "enabled": true,
        "lightStyle": "",
        "darkStyle": ""
      },
      "reverseGeocoding": {
        "enabled": true
      },
      "oauth": {
        "enabled": true,
        "issuerUrl": "https://auth.${vals_info_cluster_domain}/application/o/immich/",
        "clientId": "${secrets_apps_auth_applications_immich_clientId}",
        "clientSecret": "${secrets_apps_auth_applications_immich_clientSecret}",
        "scope": "openid email profile",
        "signingAlgorithm": "RS256",
        "storageLabelClaim": "preferred_username",
        "storageQuotaClaim": "immich_quota",
        "defaultStorageQuota": 0,
        "buttonText": "Login",
        "autoRegister": true,
        "autoLaunch": true,
        "mobileOverrideEnabled": false,
        "mobileRedirectUri": ""
      },
      "passwordLogin": {
        "enabled": false
      },
      "storageTemplate": {
        "enabled": true,
        "hashVerificationEnabled": true,
        "template": "{{y}}/{{y}}-{{MM}}-{{dd}}/{{filename}}"
      },
      "thumbnail": {
        "webpSize": 250,
        "jpegSize": 1440,
        "quality": 80,
        "colorspace": "p3"
      },
      "newVersionCheck": {
        "enabled": true
      },
      "trash": {
        "enabled": true,
        "days": 30
      },
      "theme": {
        "customCss": ""
      },
      "library": {
        "scan": {
          "enabled": true,
          "cronExpression": "0 0 * * *"
        },
        "watch": {
          "enabled": false,
          "usePolling": false,
          "interval": 10000
        }
      },
      "server": {
        "externalDomain": "photos.${vals_info_cluster_domain}",
        "loginPageMessage": ""
      },
      "user": {
        "deleteDelay": 7
      }
    }
