apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - immich_machine-learning_deployment.yaml
  - immich_machine-learning_service.yaml
  - immich_microservices_deployment.yaml
  - immich_postgresql_configmap.yaml
  - immich_postgresql_helm.yaml
  - immich_pvc.yaml
  - immich_redis_helm.yaml
  - immich_secrets.yaml
  - immich_server_deployment.yaml
  - immich_server_ingress.yaml
  - immich_server_service.yaml

secretGenerator:
  - name: immich-config
    namespace: photos
    files:
      - immich_config/immich.json
