apiVersion: v1
kind: Service
metadata:
  name: authoritative-bind-tcp
  namespace: dns
  annotations:
    metallb.universe.tf/allow-shared-ip: authoritative-bind
spec:
  type: LoadBalancer
  loadBalancerIP: ${vals_apps_dns_authoritative_ipAddress}
  selector:
    app: authoritative-bind
  ports:
    - port: 53
      targetPort: 53
      protocol: TCP
      name: dns-tcp
---
apiVersion: v1
kind: Service
metadata:
  name: authoritative-bind-udp
  namespace: dns
  annotations:
    metallb.universe.tf/allow-shared-ip: authoritative-bind
spec:
  type: LoadBalancer
  loadBalancerIP: ${vals_apps_dns_authoritative_ipAddress}
  selector:
    app: authoritative-bind
  ports:
    - port: 53
      targetPort: 53
      protocol: UDP
      name: dns-udp
