apiVersion: autoscaling.k8s.io/v1beta2
kind: VerticalPodAutoscaler
metadata:
  name: authoritative-bind-vpa
  namespace: dns
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: authoritative-bind
  updatePolicy:
    updateMode: "Off"
